-- ============================================================
-- BORA APP — EXPANSÃO CATÁLOGO PARTE 3/4
-- Chocolates · Snacks · Conservas · Molhos · Higiene · Limpeza
-- ============================================================

INSERT INTO public.products
  (id, restaurant_id, name, description, price, photo_url, is_available, category, is_popular, is_on_sale, discount_price)
VALUES

-- ── CHOCOLATES ───────────────────────────────────────────────
('ch-001','continente-guarda','Milka Leite 100g','Chocolate de leite alpino 100g',1.29,'https://source.unsplash.com/400x400/?milka,chocolate,milk',true,'Chocolates',true,false,null),
('ch-002','continente-guarda','Milka Oreo 100g','Chocolate leite recheio Oreo 100g',1.49,'https://source.unsplash.com/400x400/?milka,oreo,chocolate',true,'Chocolates',true,false,null),
('ch-003','continente-guarda','Milka Caramelo 100g','Chocolate leite com caramelo 100g',1.49,'https://source.unsplash.com/400x400/?milka,caramel,chocolate',true,'Chocolates',false,false,null),
('ch-004','continente-guarda','Milka Amêndoa 100g','Chocolate leite com amêndoas 100g',1.49,'https://source.unsplash.com/400x400/?milka,almond,chocolate',true,'Chocolates',false,false,null),
('ch-005','continente-guarda','Milka Avelã 100g','Chocolate leite com avelãs 100g',1.49,'https://source.unsplash.com/400x400/?milka,hazelnut,choc',true,'Chocolates',false,false,null),
('ch-006','continente-guarda','Milka Grande 300g','Chocolate de leite alpino 300g',3.49,'https://source.unsplash.com/400x400/?milka,large,bar',true,'Chocolates',false,false,null),
('ch-007','continente-guarda','Lindt Excellence 70% 100g','Chocolate negro 70% cacau',2.49,'https://source.unsplash.com/400x400/?lindt,dark,chocolate',true,'Chocolates',true,false,null),
('ch-008','continente-guarda','Lindt Excellence 85% 100g','Chocolate negro 85% cacau',2.49,'https://source.unsplash.com/400x400/?dark,chocolate,intense',true,'Chocolates',false,false,null),
('ch-009','continente-guarda','Lindt Lindor Leite 200g','Bombons redondos leite 200g',5.99,'https://source.unsplash.com/400x400/?lindor,truffle,chocolate',true,'Chocolates',true,false,null),
('ch-010','continente-guarda','Lindt Lindor Sortido 200g','Bombons redondos sortidos 200g',5.99,'https://source.unsplash.com/400x400/?lindor,mixed,truffle',true,'Chocolates',false,false,null),
('ch-011','continente-guarda','Toblerone Original 100g','Chocolate suíço com mel e amêndoa',2.49,'https://source.unsplash.com/400x400/?toblerone,swiss,chocolate',true,'Chocolates',true,false,null),
('ch-012','continente-guarda','Toblerone 400g','Chocolate suíço grande 400g',7.99,'https://source.unsplash.com/400x400/?toblerone,large,bar',true,'Chocolates',false,false,null),
('ch-013','continente-guarda','Snickers 50g','Barrinha caramelo amendoim 50g',0.89,'https://source.unsplash.com/400x400/?snickers,bar,peanut',true,'Chocolates',true,false,null),
('ch-014','continente-guarda','Snickers Pack 4x50g','Pack 4 barrinhas Snickers',2.99,'https://source.unsplash.com/400x400/?snickers,multipack',true,'Chocolates',false,false,null),
('ch-015','continente-guarda','Twix Original 50g','Barrinha biscoito caramelo 50g',0.89,'https://source.unsplash.com/400x400/?twix,caramel,biscuit',true,'Chocolates',true,false,null),
('ch-016','continente-guarda','Twix Pack 4x50g','Pack 4 barrinhas Twix',2.99,'https://source.unsplash.com/400x400/?twix,multipack',true,'Chocolates',false,false,null),
('ch-017','continente-guarda','Mars 51g','Barrinha nougat caramelo 51g',0.89,'https://source.unsplash.com/400x400/?mars,bar,nougat',true,'Chocolates',false,false,null),
('ch-018','continente-guarda','Bounty 57g','Barrinha coco chocolate 57g',0.89,'https://source.unsplash.com/400x400/?bounty,coconut,chocolate',true,'Chocolates',false,false,null),
('ch-019','continente-guarda','Kinder Bueno 43g','Wafer avelã leite 43g',1.09,'https://source.unsplash.com/400x400/?kinder,bueno,wafer',true,'Chocolates',true,false,null),
('ch-020','continente-guarda','Kinder Bueno White 39g','Wafer avelã chocolate branco 39g',1.09,'https://source.unsplash.com/400x400/?kinder,white,chocolate',true,'Chocolates',false,false,null),
('ch-021','continente-guarda','Kinder Chocolate 100g','Chocolate com leite recheio 100g',1.79,'https://source.unsplash.com/400x400/?kinder,bar,milk',true,'Chocolates',true,false,null),
('ch-022','continente-guarda','Kinder Surprise 20g','Ovo surpresa chocolate 20g',0.89,'https://source.unsplash.com/400x400/?kinder,surprise,egg',true,'Chocolates',true,false,null),
('ch-023','continente-guarda','Ferrero Rocher 200g','Bombons avelã chocolate 200g',5.49,'https://source.unsplash.com/400x400/?ferrero,rocher,hazelnut',true,'Chocolates',true,false,null),
('ch-024','continente-guarda','Raffaello 230g','Bombons coco amêndoa 230g',5.99,'https://source.unsplash.com/400x400/?raffaello,coconut,praline',true,'Chocolates',false,false,null),
('ch-025','continente-guarda','Nutella 400g','Creme avelã e cacau 400g',3.99,'https://source.unsplash.com/400x400/?nutella,hazelnut,spread',true,'Chocolates',true,false,null),
('ch-026','continente-guarda','Nutella 750g','Creme avelã e cacau 750g',6.99,'https://source.unsplash.com/400x400/?nutella,large,jar',true,'Chocolates',true,false,null),
('ch-027','continente-guarda','Nutella Biscuits 304g','Biscoitos Nutella recheados 304g',3.49,'https://source.unsplash.com/400x400/?nutella,biscuit,cookie',true,'Chocolates',false,false,null),
('ch-028','continente-guarda','M&Ms Amendoim 200g','Confeitos amendoim chocolate 200g',2.49,'https://source.unsplash.com/400x400/?mms,peanut,candy',true,'Chocolates',true,false,null),
('ch-029','continente-guarda','M&Ms Leite 200g','Confeitos chocolate leite 200g',2.49,'https://source.unsplash.com/400x400/?mms,milk,chocolate',true,'Chocolates',false,false,null),
('ch-030','continente-guarda','Chocolate Negro 70% Bio 80g','Chocolate negro orgânico 70%',2.99,'https://source.unsplash.com/400x400/?organic,dark,chocolate',true,'Chocolates',false,false,null),
('ch-031','continente-guarda','Nestlé After Eight 200g','Chocolate menta finos 200g',3.49,'https://source.unsplash.com/400x400/?after,eight,mint,chocolate',true,'Chocolates',false,false,null),
('ch-032','continente-guarda','Reese''s Peanut Butter 42g','Copinhos manteiga amendoim 42g',1.19,'https://source.unsplash.com/400x400/?reeses,peanut,butter',true,'Chocolates',false,false,null),
('ch-033','continente-guarda','Hershey''s Bar 40g','Chocolate americano clássico',0.99,'https://source.unsplash.com/400x400/?hersheys,classic,chocolate',true,'Chocolates',false,false,null),
('ch-034','continente-guarda','Cacau em Pó 200g','Cacau em pó puro sem açúcar',1.99,'https://source.unsplash.com/400x400/?cocoa,powder,dark',true,'Chocolates',false,false,null),
('ch-035','continente-guarda','Bombons Sortidos Caixa 250g','Caixa bombons sortidos 250g',5.99,'https://source.unsplash.com/400x400/?chocolate,box,assorted',true,'Chocolates',false,false,null),
('ch-036','continente-guarda','Continente Chocolate Leite 100g','Chocolate leite marca própria',0.69,'https://source.unsplash.com/400x400/?chocolate,economy,milk',true,'Chocolates',false,false,null),

-- ── SNACKS E APERITIVOS ──────────────────────────────────────
('sn-001','continente-guarda','Pringles Original 165g','Batatas fritas tubo original 165g',2.49,'https://source.unsplash.com/400x400/?pringles,chips,original',true,'Snacks e Aperitivos',true,false,null),
('sn-002','continente-guarda','Pringles Sal e Vinagre 165g','Batatas fritas sal e vinagre 165g',2.49,'https://source.unsplash.com/400x400/?pringles,salt,vinegar',true,'Snacks e Aperitivos',false,false,null),
('sn-003','continente-guarda','Pringles Queijo 165g','Batatas fritas queijo 165g',2.49,'https://source.unsplash.com/400x400/?pringles,cheese,chips',true,'Snacks e Aperitivos',false,false,null),
('sn-004','continente-guarda','Pringles BBQ 165g','Batatas fritas barbecue 165g',2.49,'https://source.unsplash.com/400x400/?pringles,bbq,barbecue',true,'Snacks e Aperitivos',false,false,null),
('sn-005','continente-guarda','Lay''s Original 160g','Batatas fritas onduladas 160g',1.99,'https://source.unsplash.com/400x400/?lays,chips,potato',true,'Snacks e Aperitivos',true,false,null),
('sn-006','continente-guarda','Lay''s Paprika 160g','Batatas fritas paprika 160g',1.99,'https://source.unsplash.com/400x400/?lays,paprika,chips',true,'Snacks e Aperitivos',false,false,null),
('sn-007','continente-guarda','Lay''s Queijo Cheddar 160g','Batatas fritas queijo cheddar',1.99,'https://source.unsplash.com/400x400/?lays,cheddar,chips',true,'Snacks e Aperitivos',false,false,null),
('sn-008','continente-guarda','Doritos Nacho Cheese 200g','Snack milho queijo 200g',2.29,'https://source.unsplash.com/400x400/?doritos,nacho,cheese',true,'Snacks e Aperitivos',true,false,null),
('sn-009','continente-guarda','Doritos Cool Original 200g','Snack milho original 200g',2.29,'https://source.unsplash.com/400x400/?doritos,cool,ranch',true,'Snacks e Aperitivos',false,false,null),
('sn-010','continente-guarda','Doritos BBQ 200g','Snack milho barbecue 200g',2.29,'https://source.unsplash.com/400x400/?doritos,bbq,tortilla',true,'Snacks e Aperitivos',false,false,null),
('sn-011','continente-guarda','Ruffles Original 170g','Batatas onduladas clássicas 170g',1.99,'https://source.unsplash.com/400x400/?ruffles,wavy,chips',true,'Snacks e Aperitivos',false,false,null),
('sn-012','continente-guarda','Cheetos 90g','Snack de milho queijo 90g',1.39,'https://source.unsplash.com/400x400/?cheetos,cheese,puffs',true,'Snacks e Aperitivos',true,false,null),
('sn-013','continente-guarda','Popchips Original 85g','Chips de batata sem fritar 85g',2.49,'https://source.unsplash.com/400x400/?popchips,baked,chips',true,'Snacks e Aperitivos',false,false,null),
('sn-014','continente-guarda','Mikado Original 75g','Palitos de bolacha com chocolate',1.49,'https://source.unsplash.com/400x400/?mikado,pocky,chocolate',true,'Snacks e Aperitivos',false,false,null),
('sn-015','continente-guarda','Papo-Secos 4un','Papo-secos frescos 4 unidades',0.89,'https://source.unsplash.com/400x400/?bread,roll,soft',true,'Snacks e Aperitivos',false,false,null),
('sn-016','continente-guarda','Amendoins Torrados Salgados 200g','Amendoins torrados salgados 200g',1.29,'https://source.unsplash.com/400x400/?peanuts,salted,roasted',true,'Snacks e Aperitivos',true,false,null),
('sn-017','continente-guarda','Amendoins Mel 200g','Amendoins com mel 200g',1.49,'https://source.unsplash.com/400x400/?peanuts,honey,roasted',true,'Snacks e Aperitivos',false,false,null),
('sn-018','continente-guarda','Pistácio Torrado 150g','Pistácio com casca torrado 150g',3.49,'https://source.unsplash.com/400x400/?pistachios,roasted,shell',true,'Snacks e Aperitivos',false,false,null),
('sn-019','continente-guarda','Mix Frutos Secos 200g','Mix castanhas e frutos secos 200g',2.99,'https://source.unsplash.com/400x400/?mixed,nuts,dried',true,'Snacks e Aperitivos',false,false,null),
('sn-020','continente-guarda','Pipocas Manteiga 100g','Pipocas sabor manteiga 100g',1.49,'https://source.unsplash.com/400x400/?popcorn,butter,microwave',true,'Snacks e Aperitivos',true,false,null),
('sn-021','continente-guarda','Pipocas Caramelo 100g','Pipocas sabor caramelo 100g',1.49,'https://source.unsplash.com/400x400/?popcorn,caramel,sweet',true,'Snacks e Aperitivos',false,false,null),
('sn-022','continente-guarda','Pipocas Micro-ondas Sal 3x85g','Pack pipocas micro-ondas 3 un.',2.29,'https://source.unsplash.com/400x400/?microwave,popcorn,pack',true,'Snacks e Aperitivos',false,false,null),
('sn-023','continente-guarda','Nachos Salsa 200g','Nachos com molho salsa 200g',2.99,'https://source.unsplash.com/400x400/?nachos,salsa,dip',true,'Snacks e Aperitivos',false,false,null),
('sn-024','continente-guarda','Batata Chips Continente 150g','Batatas fritas marca própria 150g',0.99,'https://source.unsplash.com/400x400/?chips,economy,potato',true,'Snacks e Aperitivos',false,false,null),
('sn-025','continente-guarda','Torresmos 100g','Torresmos aperitivo 100g',2.49,'https://source.unsplash.com/400x400/?pork,rinds,crispy',true,'Snacks e Aperitivos',false,false,null),
('sn-026','continente-guarda','Cereais para Aperitivo 200g','Mix cereal salgado aperitivo',1.49,'https://source.unsplash.com/400x400/?cereal,snack,mix',true,'Snacks e Aperitivos',false,false,null),
('sn-027','continente-guarda','Tremoços em Salmoura 500g','Tremoços aperitivo português 500g',1.79,'https://source.unsplash.com/400x400/?lupin,beans,snack',true,'Snacks e Aperitivos',true,false,null),
('sn-028','continente-guarda','Azeitonas Verdes com Caroço 340g','Azeitonas verdes portuguesas 340g',1.99,'https://source.unsplash.com/400x400/?green,olives,jar',true,'Snacks e Aperitivos',true,false,null),
('sn-029','continente-guarda','Azeitonas Pretas Fatiadas 185g','Azeitonas pretas fatiadas 185g',1.49,'https://source.unsplash.com/400x400/?black,olives,sliced',true,'Snacks e Aperitivos',false,false,null),
('sn-030','continente-guarda','Paté de Atum 75g','Paté de atum aperitivo 75g',0.89,'https://source.unsplash.com/400x400/?tuna,pate,spread',true,'Snacks e Aperitivos',true,false,null),

-- ── CONSERVAS ────────────────────────────────────────────────
('cn-001','continente-guarda','Atum em Azeite Rio Mare 80g','Atum em azeite premium 80g',2.49,'https://source.unsplash.com/400x400/?tuna,olive,oil,can',true,'Conservas',true,false,null),
('cn-002','continente-guarda','Atum Natural Migas 120g','Atum ao natural em pedaços 120g',1.49,'https://source.unsplash.com/400x400/?tuna,natural,can',true,'Conservas',true,false,null),
('cn-003','continente-guarda','Atum Azeite 3x80g','Pack atum em azeite 3 latas',4.49,'https://source.unsplash.com/400x400/?tuna,pack,three',true,'Conservas',true,false,null),
('cn-004','continente-guarda','Sardinha em Azeite 125g','Sardinha portuguesa em azeite 125g',0.99,'https://source.unsplash.com/400x400/?sardines,olive,oil',true,'Conservas',true,false,null),
('cn-005','continente-guarda','Sardinha Tomate 125g','Sardinha em tomate 125g',0.89,'https://source.unsplash.com/400x400/?sardines,tomato',true,'Conservas',true,false,null),
('cn-006','continente-guarda','Sardinha Picante 125g','Sardinha picante em azeite 125g',0.99,'https://source.unsplash.com/400x400/?sardines,spicy,can',true,'Conservas',false,false,null),
('cn-007','continente-guarda','Cavala em Azeite 120g','Cavala em azeite 120g',1.09,'https://source.unsplash.com/400x400/?mackerel,olive,oil',true,'Conservas',false,false,null),
('cn-008','continente-guarda','Polvo em Azeite 115g','Polvo em azeite e alho 115g',2.49,'https://source.unsplash.com/400x400/?octopus,olive,garlic',true,'Conservas',false,false,null),
('cn-009','continente-guarda','Tomate Pelado Inteiro 400g','Tomate pelado italiano 400g',0.89,'https://source.unsplash.com/400x400/?peeled,tomato,can',true,'Conservas',true,false,null),
('cn-010','continente-guarda','Tomate Triturado 400g','Tomate triturado polpa 400g',0.79,'https://source.unsplash.com/400x400/?crushed,tomato,can',true,'Conservas',true,false,null),
('cn-011','continente-guarda','Concentrado de Tomate 140g','Concentrado tomate duplo 140g',0.79,'https://source.unsplash.com/400x400/?tomato,paste,concentrate',true,'Conservas',true,false,null),
('cn-012','continente-guarda','Milho Cozido 285g','Milho amarelo cozido 285g',0.79,'https://source.unsplash.com/400x400/?corn,sweet,can',true,'Conservas',true,false,null),
('cn-013','continente-guarda','Feijão Vermelho 400g','Feijão vermelho cozido 400g',0.89,'https://source.unsplash.com/400x400/?red,kidney,beans,can',true,'Conservas',true,false,null),
('cn-014','continente-guarda','Feijão Branco 400g','Feijão branco cozido 400g',0.89,'https://source.unsplash.com/400x400/?white,beans,cooked',true,'Conservas',false,false,null),
('cn-015','continente-guarda','Grão Cozido 400g','Grão de bico cozido 400g',0.89,'https://source.unsplash.com/400x400/?chickpeas,cooked,can',true,'Conservas',true,false,null),
('cn-016','continente-guarda','Lentilhas Cozidas 400g','Lentilhas verdes cozidas 400g',0.89,'https://source.unsplash.com/400x400/?lentils,cooked,green',true,'Conservas',false,false,null),
('cn-017','continente-guarda','Espargos Brancos 212g','Espargos brancos em conserva 212g',1.49,'https://source.unsplash.com/400x400/?asparagus,white,can',true,'Conservas',false,false,null),
('cn-018','continente-guarda','Cogumelos Laminados 400g','Cogumelos laminados em água 400g',1.29,'https://source.unsplash.com/400x400/?mushrooms,sliced,can',true,'Conservas',false,false,null),
('cn-019','continente-guarda','Ananás em Calda 565g','Rodelas ananás em calda 565g',1.49,'https://source.unsplash.com/400x400/?pineapple,syrup,can',true,'Conservas',false,false,null),
('cn-020','continente-guarda','Pêssego em Calda 480g','Metades pêssego em calda 480g',1.29,'https://source.unsplash.com/400x400/?peach,syrup,canned',true,'Conservas',false,false,null),
('cn-021','continente-guarda','Cocktail de Frutas 480g','Mix frutas em calda 480g',1.29,'https://source.unsplash.com/400x400/?fruit,cocktail,can',true,'Conservas',false,false,null),
('cn-022','continente-guarda','Frango ao Natural 170g','Frango cozido ao natural 170g',2.49,'https://source.unsplash.com/400x400/?chicken,canned,natural',true,'Conservas',false,false,null),
('cn-023','continente-guarda','Sopa de Peixe 400g','Sopa de peixe conserva 400g',1.99,'https://source.unsplash.com/400x400/?fish,soup,can',true,'Conservas',false,false,null),
('cn-024','continente-guarda','Bacalhau em Azeite 120g','Migas de bacalhau em azeite 120g',3.49,'https://source.unsplash.com/400x400/?codfish,olive,oil,can',true,'Conservas',false,false,null),

-- ── MOLHOS E CONDIMENTOS ─────────────────────────────────────
('mc-001','continente-guarda','Heinz Ketchup 570g','Ketchup tomate clássico 570g',2.99,'https://source.unsplash.com/400x400/?ketchup,heinz,tomato',true,'Molhos e Condimentos',true,false,null),
('mc-002','continente-guarda','Heinz Ketchup 1kg','Ketchup tomate família 1kg',4.99,'https://source.unsplash.com/400x400/?ketchup,large,bottle',true,'Molhos e Condimentos',false,false,null),
('mc-003','continente-guarda','Heinz Ketchup Light 570g','Ketchup tomate sem açúcar adicionado',2.99,'https://source.unsplash.com/400x400/?ketchup,light,tomato',true,'Molhos e Condimentos',false,false,null),
('mc-004','continente-guarda','Calvé Maionese 400ml','Maionese cremosa 400ml',2.49,'https://source.unsplash.com/400x400/?mayonnaise,cream,sauce',true,'Molhos e Condimentos',true,false,null),
('mc-005','continente-guarda','Calvé Maionese Light 400ml','Maionese light 50% menos calorias',2.49,'https://source.unsplash.com/400x400/?light,mayo,sauce',true,'Molhos e Condimentos',false,false,null),
('mc-006','continente-guarda','Calvé Mostarda 250g','Mostarda amarela clássica 250g',1.29,'https://source.unsplash.com/400x400/?mustard,yellow,classic',true,'Molhos e Condimentos',true,false,null),
('mc-007','continente-guarda','Calvé Mostarda Dijon 200g','Mostarda dijon francesa 200g',1.99,'https://source.unsplash.com/400x400/?dijon,mustard,french',true,'Molhos e Condimentos',false,false,null),
('mc-008','continente-guarda','Tabasco Picante 60ml','Molho picante tabasco 60ml',2.49,'https://source.unsplash.com/400x400/?tabasco,hot,sauce',true,'Molhos e Condimentos',false,false,null),
('mc-009','continente-guarda','Kikkoman Molho Soja 150ml','Molho de soja japonês 150ml',2.29,'https://source.unsplash.com/400x400/?soy,sauce,japanese',true,'Molhos e Condimentos',false,false,null),
('mc-010','continente-guarda','Kikkoman Molho Soja 250ml','Molho de soja japonês 250ml',2.99,'https://source.unsplash.com/400x400/?soy,sauce,bottle',true,'Molhos e Condimentos',false,false,null),
('mc-011','continente-guarda','Worcestershire Sauce 150ml','Molho inglês picante 150ml',2.49,'https://source.unsplash.com/400x400/?worcestershire,sauce,bottle',true,'Molhos e Condimentos',false,false,null),
('mc-012','continente-guarda','Molho Barbecue HP 500ml','Molho barbecue americano 500ml',2.99,'https://source.unsplash.com/400x400/?bbq,sauce,smoky',true,'Molhos e Condimentos',false,false,null),
('mc-013','continente-guarda','Molho Piri-Piri Continente 200ml','Molho piri-piri português 200ml',1.49,'https://source.unsplash.com/400x400/?piri,piri,sauce,hot',true,'Molhos e Condimentos',true,false,null),
('mc-014','continente-guarda','Maggi Molho de Galinha 100ml','Aroma líquido para culinária 100ml',1.29,'https://source.unsplash.com/400x400/?maggi,liquid,seasoning',true,'Molhos e Condimentos',false,false,null),
('mc-015','continente-guarda','Vinagre Balsâmico 250ml','Vinagre balsâmico de Módena 250ml',2.49,'https://source.unsplash.com/400x400/?balsamic,vinegar,dark',true,'Molhos e Condimentos',false,false,null),
('mc-016','continente-guarda','Vinagre de Maçã 500ml','Vinagre de maçã natural 500ml',1.99,'https://source.unsplash.com/400x400/?apple,cider,vinegar',true,'Molhos e Condimentos',false,false,null),
('mc-017','continente-guarda','Pesto Rosso 190g','Pesto tomate seco e manjericão',2.99,'https://source.unsplash.com/400x400/?pesto,rosso,red',true,'Molhos e Condimentos',false,false,null),
('mc-018','continente-guarda','Pesto Genovês 190g','Pesto manjericão e pinhões 190g',2.99,'https://source.unsplash.com/400x400/?pesto,basil,green',true,'Molhos e Condimentos',true,false,null),
('mc-019','continente-guarda','Molho Bolonhesa Barilla 400g','Molho massa bolonhesa 400g',1.99,'https://source.unsplash.com/400x400/?bolognese,sauce,pasta',true,'Molhos e Condimentos',true,false,null),
('mc-020','continente-guarda','Molho Carbonara Barilla 400g','Molho carbonara cremoso 400g',2.29,'https://source.unsplash.com/400x400/?carbonara,cream,sauce',true,'Molhos e Condimentos',false,false,null),
('mc-021','continente-guarda','Molho Arrabiata Barilla 400g','Molho picante tomate 400g',1.99,'https://source.unsplash.com/400x400/?arrabiata,tomato,sauce',true,'Molhos e Condimentos',false,false,null),
('mc-022','continente-guarda','Sriracha Huy Fong 200ml','Molho picante tailandês 200ml',2.99,'https://source.unsplash.com/400x400/?sriracha,hot,chili,sauce',true,'Molhos e Condimentos',false,false,null),
('mc-023','continente-guarda','Knorr Cubo de Galinha 8un','Cubos de caldo de galinha 8 un',1.29,'https://source.unsplash.com/400x400/?bouillon,cube,chicken',true,'Molhos e Condimentos',true,false,null),
('mc-024','continente-guarda','Knorr Cubo de Carne 8un','Cubos de caldo de carne 8 un',1.29,'https://source.unsplash.com/400x400/?bouillon,beef,cube',true,'Molhos e Condimentos',true,false,null),
('mc-025','continente-guarda','Sal Rosa Himalaia 500g','Sal rosa do Himalaia fino 500g',3.49,'https://source.unsplash.com/400x400/?himalayan,pink,salt',true,'Molhos e Condimentos',false,false,null),

-- ── HIGIENE PESSOAL ──────────────────────────────────────────
('hi-001','continente-guarda','Pantene Shampoo Reparação 400ml','Shampoo reparação e proteção 400ml',4.99,'https://source.unsplash.com/400x400/?shampoo,hair,bottle',true,'Higiene Pessoal',true,false,null),
('hi-002','continente-guarda','Pantene Shampoo Hidratação 400ml','Shampoo hidratação intensa 400ml',4.99,'https://source.unsplash.com/400x400/?shampoo,moisturizing',true,'Higiene Pessoal',false,false,null),
('hi-003','continente-guarda','Head & Shoulders Clássico 400ml','Shampoo anticaspa 400ml',5.49,'https://source.unsplash.com/400x400/?head,shoulders,dandruff',true,'Higiene Pessoal',true,false,null),
('hi-004','continente-guarda','Head & Shoulders Menthol 400ml','Shampoo anticaspa mentol 400ml',5.49,'https://source.unsplash.com/400x400/?head,shoulders,menthol',true,'Higiene Pessoal',false,false,null),
('hi-005','continente-guarda','Elseve Shampoo Extraordinário 400ml','Shampoo nutritivo L''Oréal 400ml',5.99,'https://source.unsplash.com/400x400/?loreal,shampoo,hair',true,'Higiene Pessoal',false,false,null),
('hi-006','continente-guarda','Dove Shampoo Hidratação Intensa 400ml','Shampoo hidratação intensiva 400ml',4.79,'https://source.unsplash.com/400x400/?dove,shampoo,moisturize',true,'Higiene Pessoal',false,false,null),
('hi-007','continente-guarda','Herbal Essences Argan 400ml','Shampoo argan natural 400ml',4.99,'https://source.unsplash.com/400x400/?herbal,essences,argan',true,'Higiene Pessoal',false,false,null),
('hi-008','continente-guarda','Pantene Amaciador 200ml','Amaciador reparação 200ml',3.99,'https://source.unsplash.com/400x400/?conditioner,hair,care',true,'Higiene Pessoal',false,false,null),
('hi-009','continente-guarda','Dove Gel de Banho Hidratante 500ml','Gel banho hidratante 500ml',3.49,'https://source.unsplash.com/400x400/?dove,shower,gel,body',true,'Higiene Pessoal',true,false,null),
('hi-010','continente-guarda','Dove Gel de Banho Sensitive 500ml','Gel banho pele sensível 500ml',3.49,'https://source.unsplash.com/400x400/?dove,sensitive,shower',true,'Higiene Pessoal',false,false,null),
('hi-011','continente-guarda','Nivea Gel de Banho Men 500ml','Gel banho masculino 500ml',3.49,'https://source.unsplash.com/400x400/?nivea,men,shower,gel',true,'Higiene Pessoal',true,false,null),
('hi-012','continente-guarda','Palmolive Gel de Banho 500ml','Gel banho hidratante 500ml',2.99,'https://source.unsplash.com/400x400/?palmolive,shower,body',true,'Higiene Pessoal',false,false,null),
('hi-013','continente-guarda','Fa Gel Duche Paraíso Tropical 400ml','Gel banho tropical 400ml',2.79,'https://source.unsplash.com/400x400/?fa,shower,gel,tropical',true,'Higiene Pessoal',false,false,null),
('hi-014','continente-guarda','Colgate Total Pasta 75ml','Pasta dentes proteção total 75ml',2.49,'https://source.unsplash.com/400x400/?colgate,toothpaste,white',true,'Higiene Pessoal',true,false,null),
('hi-015','continente-guarda','Colgate Total Pasta 125ml','Pasta dentes proteção total 125ml',3.49,'https://source.unsplash.com/400x400/?toothpaste,dental,care',true,'Higiene Pessoal',true,false,null),
('hi-016','continente-guarda','Colgate Max White 75ml','Pasta branqueadora 75ml',3.49,'https://source.unsplash.com/400x400/?whitening,toothpaste',true,'Higiene Pessoal',false,false,null),
('hi-017','continente-guarda','Oral-B Pasta Dentes 75ml','Pasta dentes fluoreto 75ml',2.99,'https://source.unsplash.com/400x400/?oralb,toothpaste,fluoride',true,'Higiene Pessoal',false,false,null),
('hi-018','continente-guarda','Signal Pasta Dentes 75ml','Pasta dentes branqueadora 75ml',1.99,'https://source.unsplash.com/400x400/?signal,toothpaste',true,'Higiene Pessoal',false,false,null),
('hi-019','continente-guarda','Colgate Escova Média','Escova dentes macia 1 un',1.49,'https://source.unsplash.com/400x400/?toothbrush,medium',true,'Higiene Pessoal',true,false,null),
('hi-020','continente-guarda','Oral-B Escova Precision','Escova dentes precision clean',2.49,'https://source.unsplash.com/400x400/?toothbrush,precision',true,'Higiene Pessoal',false,false,null),
('hi-021','continente-guarda','Listerine Colutório Total Care 500ml','Elixir bucal total 500ml',5.49,'https://source.unsplash.com/400x400/?listerine,mouthwash,green',true,'Higiene Pessoal',true,false,null),
('hi-022','continente-guarda','Listerine Cool Mint 500ml','Elixir bucal menta fresca 500ml',5.49,'https://source.unsplash.com/400x400/?listerine,cool,mint',true,'Higiene Pessoal',false,false,null),
('hi-023','continente-guarda','Gillette Fusion5 Recarga 4un','Recarga lâminas Fusion5 4 un',10.99,'https://source.unsplash.com/400x400/?gillette,razor,blade',true,'Higiene Pessoal',true,false,null),
('hi-024','continente-guarda','Gillette Mach3 Recarga 4un','Recarga lâminas Mach3 4 un',8.99,'https://source.unsplash.com/400x400/?mach3,razor,shaving',true,'Higiene Pessoal',false,false,null),
('hi-025','continente-guarda','Gillette Gel Barbear 200ml','Gel de barbear sensitive 200ml',3.99,'https://source.unsplash.com/400x400/?shaving,gel,foam',true,'Higiene Pessoal',false,false,null),
('hi-026','continente-guarda','Veet Creme Depilatório 200ml','Creme depilatório pernas 200ml',4.99,'https://source.unsplash.com/400x400/?hair,removal,cream',true,'Higiene Pessoal',false,false,null),
('hi-027','continente-guarda','Nivea Desodorizante Roll-On 50ml','Desodorizante rolha 48h 50ml',3.49,'https://source.unsplash.com/400x400/?deodorant,roll,on,nivea',true,'Higiene Pessoal',true,false,null),
('hi-028','continente-guarda','Dove Desodorizante Spray 150ml','Desodorizante spray 48h 150ml',3.29,'https://source.unsplash.com/400x400/?dove,deodorant,spray',true,'Higiene Pessoal',true,false,null),
('hi-029','continente-guarda','Rexona Men Desodorizante 150ml','Desodorizante masculino spray 150ml',3.29,'https://source.unsplash.com/400x400/?rexona,men,deodorant',true,'Higiene Pessoal',true,false,null),
('hi-030','continente-guarda','Axe Desodorizante Dark Temptation 150ml','Desodorizante masculino 150ml',3.49,'https://source.unsplash.com/400x400/?axe,deodorant,dark',true,'Higiene Pessoal',false,false,null),
('hi-031','continente-guarda','Nivea Creme Hidratante 200ml','Creme hidratante pele 200ml',3.99,'https://source.unsplash.com/400x400/?nivea,cream,moisturizer',true,'Higiene Pessoal',true,false,null),
('hi-032','continente-guarda','Vaseline Lip Therapy 20g','Bálsamo labial hidratante 20g',2.49,'https://source.unsplash.com/400x400/?vaseline,lip,balm',true,'Higiene Pessoal',false,false,null),
('hi-033','continente-guarda','Protetor Solar SPF50 200ml','Protetor solar corpo SPF50 200ml',7.99,'https://source.unsplash.com/400x400/?sunscreen,spf,protection',true,'Higiene Pessoal',true,false,null),
('hi-034','continente-guarda','Protetor Solar Rosto SPF30 50ml','Protetor solar rosto SPF30 50ml',5.99,'https://source.unsplash.com/400x400/?face,sunscreen,spf30',true,'Higiene Pessoal',false,false,null),
('hi-035','continente-guarda','Tampões OB Normal 32un','Tampões internos normal 32 un',3.99,'https://source.unsplash.com/400x400/?tampon,feminine,hygiene',true,'Higiene Pessoal',true,false,null),
('hi-036','continente-guarda','Pensos Always Ultra Normal 16un','Pensos higiénicos normal 16 un',2.99,'https://source.unsplash.com/400x400/?pads,feminine,always',true,'Higiene Pessoal',true,false,null),
('hi-037','continente-guarda','Tampões Tampax Pearl 20un','Tampões Pearl com aplicador 20 un',5.49,'https://source.unsplash.com/400x400/?tampax,pearl,tampons',true,'Higiene Pessoal',false,false,null),
('hi-038','continente-guarda','Lenços Johnson''s Baby 56un','Lenços húmidos bebé 56 un',2.29,'https://source.unsplash.com/400x400/?baby,wipes,gentle',true,'Higiene Pessoal',false,false,null),
('hi-039','continente-guarda','Algodão Hidrófilo 100g','Algodão hidrófilo 100g',1.49,'https://source.unsplash.com/400x400/?cotton,pads,white',true,'Higiene Pessoal',false,false,null),
('hi-040','continente-guarda','Cotonetes 100un','Cotonetes de higiene 100 un',1.29,'https://source.unsplash.com/400x400/?cotton,swabs,earbuds',true,'Higiene Pessoal',false,false,null),
('hi-041','continente-guarda','Elidor Creme de Mãos 75ml','Creme de mãos hidratante 75ml',1.99,'https://source.unsplash.com/400x400/?hand,cream,moisturizing',true,'Higiene Pessoal',false,false,null),
('hi-042','continente-guarda','Creme de Barbear Barbasol 198g','Espuma barbear clássica 198g',2.99,'https://source.unsplash.com/400x400/?shaving,cream,barbasol',true,'Higiene Pessoal',false,false,null),

-- ── LIMPEZA ──────────────────────────────────────────────────
('lp-001','continente-guarda','Ariel Detergente Pó 2.25kg','Detergente roupa pó original 2.25kg',9.99,'https://source.unsplash.com/400x400/?laundry,detergent,powder',true,'Limpeza',true,false,null),
('lp-002','continente-guarda','Ariel Detergente Líquido 1.98L','Detergente roupa líquido 1.98L',9.99,'https://source.unsplash.com/400x400/?liquid,detergent,laundry',true,'Limpeza',true,false,null),
('lp-003','continente-guarda','Ariel Pods 3 em 1 30un','Cápsulas detergente roupa 30 un',9.99,'https://source.unsplash.com/400x400/?ariel,pods,capsule',true,'Limpeza',true,false,null),
('lp-004','continente-guarda','Skip Detergente Pó 2kg','Detergente roupa pó 2kg',7.99,'https://source.unsplash.com/400x400/?skip,washing,powder',true,'Limpeza',false,false,null),
('lp-005','continente-guarda','Persil Detergente Líquido 1.5L','Detergente roupa líquido 1.5L',7.49,'https://source.unsplash.com/400x400/?persil,liquid,detergent',true,'Limpeza',false,false,null),
('lp-006','continente-guarda','Bold 2 em 1 Pó 2.25kg','Detergente e amaciador pó 2.25kg',8.49,'https://source.unsplash.com/400x400/?bold,detergent,laundry',true,'Limpeza',false,false,null),
('lp-007','continente-guarda','Lenor Amaciador Primavera 1.65L','Amaciador primavera 1.65L',5.99,'https://source.unsplash.com/400x400/?lenor,softener,spring',true,'Limpeza',true,false,null),
('lp-008','continente-guarda','Comfort Amaciador 1.5L','Amaciador roupa 1.5L',4.99,'https://source.unsplash.com/400x400/?comfort,fabric,softener',true,'Limpeza',false,false,null),
('lp-009','continente-guarda','Fairy Original Detergente Loiça 500ml','Detergente lava-louça 500ml',2.99,'https://source.unsplash.com/400x400/?fairy,dishwashing,liquid',true,'Limpeza',true,false,null),
('lp-010','continente-guarda','Fairy Lava-Louça 1L','Detergente lava-louça 1L',4.99,'https://source.unsplash.com/400x400/?dish,soap,washing',true,'Limpeza',true,false,null),
('lp-011','continente-guarda','Sun Pastilhas Máquina Loiça 40un','Pastilhas máquina loiça 40 un',7.99,'https://source.unsplash.com/400x400/?dishwasher,tablets,sun',true,'Limpeza',true,false,null),
('lp-012','continente-guarda','Finish Quantum 40un','Pastilhas máquina loiça quantum 40un',9.99,'https://source.unsplash.com/400x400/?finish,quantum,dishwasher',true,'Limpeza',true,false,null),
('lp-013','continente-guarda','Domestos Original 750ml','Lixívia desinfetante original 750ml',2.49,'https://source.unsplash.com/400x400/?bleach,domestos,clean',true,'Limpeza',true,false,null),
('lp-014','continente-guarda','Domestos Extended Power 750ml','Lixívia espessa desinfetante 750ml',2.79,'https://source.unsplash.com/400x400/?bleach,thick,disinfect',true,'Limpeza',false,false,null),
('lp-015','continente-guarda','Mr. Muscle Banheiro 500ml','Limpador banheiro spray 500ml',2.99,'https://source.unsplash.com/400x400/?bathroom,cleaner,spray',true,'Limpeza',false,false,null),
('lp-016','continente-guarda','Mr. Muscle Cozinha 500ml','Limpador cozinha spray 500ml',2.99,'https://source.unsplash.com/400x400/?kitchen,cleaner,spray',true,'Limpeza',false,false,null),
('lp-017','continente-guarda','Mr. Muscle Vidros 500ml','Limpador vidros 500ml',2.99,'https://source.unsplash.com/400x400/?glass,cleaner,spray',true,'Limpeza',false,false,null),
('lp-018','continente-guarda','Flash Limpa-Tudo Lavanda 1L','Limpa tudo multiusos 1L',2.49,'https://source.unsplash.com/400x400/?floor,cleaner,lavender',true,'Limpeza',false,false,null),
('lp-019','continente-guarda','Vim Creme Multiusos 500ml','Creme limpador multiusos 500ml',1.99,'https://source.unsplash.com/400x400/?vim,cream,cleaner',true,'Limpeza',false,false,null),
('lp-020','continente-guarda','Harpic Power Plus 750ml','Limpador sanita 750ml',2.49,'https://source.unsplash.com/400x400/?harpic,toilet,cleaner',true,'Limpeza',false,false,null),
('lp-021','continente-guarda','Viakal Anticlacário 500ml','Limpa calcário spray 500ml',3.49,'https://source.unsplash.com/400x400/?limescale,remover,spray',true,'Limpeza',false,false,null),
('lp-022','continente-guarda','Febreze Spray Tecidos 300ml','Eliminador odores tecidos 300ml',4.49,'https://source.unsplash.com/400x400/?febreze,fabric,freshener',true,'Limpeza',false,false,null),
('lp-023','continente-guarda','Ambi Pur Car Refill 7ml','Refill ambientador carro 7ml',3.99,'https://source.unsplash.com/400x400/?car,air,freshener',true,'Limpeza',false,false,null),
('lp-024','continente-guarda','Esponjas Scotch-Brite 3un','Esponjas dupla face 3 un',2.29,'https://source.unsplash.com/400x400/?sponge,scotch,brite',true,'Limpeza',true,false,null),
('lp-025','continente-guarda','Panos de Cozinha Multiusos 3un','Panos multiusos absorventes 3 un',1.99,'https://source.unsplash.com/400x400/?cleaning,cloth,multi',true,'Limpeza',false,false,null),
('lp-026','continente-guarda','Sacos do Lixo 50L 20un','Sacos lixo pretos 50L 20 un',1.99,'https://source.unsplash.com/400x400/?trash,bag,black',true,'Limpeza',true,false,null),
('lp-027','continente-guarda','Sacos do Lixo 100L 10un','Sacos lixo pretos 100L 10 un',2.49,'https://source.unsplash.com/400x400/?garbage,bag,large',true,'Limpeza',false,false,null),
('lp-028','continente-guarda','Cillit Bang Power Cleaner 750ml','Limpador potente spray 750ml',3.49,'https://source.unsplash.com/400x400/?cillit,bang,cleaner',true,'Limpeza',false,false,null),
('lp-029','continente-guarda','Ace Lixívia Roupa Branca 1L','Lixívia para roupa branca 1L',1.99,'https://source.unsplash.com/400x400/?bleach,white,clothes',true,'Limpeza',false,false,null),
('lp-030','continente-guarda','Esfregão Chão Vileda 1un','Esfregão de chão profissional',5.99,'https://source.unsplash.com/400x400/?mop,floor,cleaning',true,'Limpeza',false,false,null)

ON CONFLICT (id) DO NOTHING;
