-- ============================================================
-- BORA APP — EXPANSÃO CATÁLOGO PARTE 2/4
-- Vinho · Espirituosas · Café · Chá · Cereais · Bolachas
-- ============================================================

INSERT INTO public.products
  (id, restaurant_id, name, description, price, photo_url, is_available, category, is_popular, is_on_sale, discount_price)
VALUES

-- ── VINHO ────────────────────────────────────────────────────
('vn-001','continente-guarda','Esporão Reserva Tinto 75cl','Vinho tinto alentejano reserva',7.99,'https://source.unsplash.com/400x400/?red,wine,bottle',true,'Vinho',true,false,null),
('vn-002','continente-guarda','Esporão Reserva Branco 75cl','Vinho branco alentejano reserva',7.99,'https://source.unsplash.com/400x400/?white,wine,bottle',true,'Vinho',true,false,null),
('vn-003','continente-guarda','Esporão Monte Velho Tinto 75cl','Vinho tinto alentejano',4.99,'https://source.unsplash.com/400x400/?wine,red,alentejo',true,'Vinho',true,false,null),
('vn-004','continente-guarda','Porta da Ravessa Tinto 75cl','Vinho tinto alentejano económico',3.49,'https://source.unsplash.com/400x400/?wine,table,red',true,'Vinho',false,false,null),
('vn-005','continente-guarda','Porta da Ravessa Branco 75cl','Vinho branco alentejano económico',3.49,'https://source.unsplash.com/400x400/?white,table,wine',true,'Vinho',false,false,null),
('vn-006','continente-guarda','Casal Garcia Branco 75cl','Vinho verde branco espumante',4.49,'https://source.unsplash.com/400x400/?vinho,verde,white',true,'Vinho',true,false,null),
('vn-007','continente-guarda','Casal Garcia Rosé 75cl','Vinho verde rosé',4.49,'https://source.unsplash.com/400x400/?rose,wine,pink',true,'Vinho',true,false,null),
('vn-008','continente-guarda','Gazela Vinho Verde 75cl','Vinho verde branco suave',3.99,'https://source.unsplash.com/400x400/?gazela,wine',true,'Vinho',false,false,null),
('vn-009','continente-guarda','Mateus Rosé 75cl','Vinho rosé português clássico',4.99,'https://source.unsplash.com/400x400/?mateus,rose',true,'Vinho',true,false,null),
('vn-010','continente-guarda','Mateus Rosé 1.875L','Vinho rosé garrafa magnum',14.99,'https://source.unsplash.com/400x400/?magnum,rose,wine',true,'Vinho',false,false,null),
('vn-011','continente-guarda','Pêra Manca Branco 75cl','Vinho branco premium Alentejo',28.99,'https://source.unsplash.com/400x400/?premium,white,wine',true,'Vinho',false,false,null),
('vn-012','continente-guarda','Herdade do Esporão 75cl','Vinho tinto Alentejo DOC',12.99,'https://source.unsplash.com/400x400/?esporao,wine,dark',true,'Vinho',false,false,null),
('vn-013','continente-guarda','Quinta do Crasto Tinto 75cl','Vinho tinto Douro',9.99,'https://source.unsplash.com/400x400/?douro,red,wine',true,'Vinho',false,false,null),
('vn-014','continente-guarda','Barca Velha 75cl','Vinho tinto Douro premium',89.99,'https://source.unsplash.com/400x400/?premium,douro,wine',true,'Vinho',false,false,null),
('vn-015','continente-guarda','Grão Vasco Tinto 75cl','Vinho tinto Dão',5.49,'https://source.unsplash.com/400x400/?dao,red,wine',true,'Vinho',false,false,null),
('vn-016','continente-guarda','Grão Vasco Branco 75cl','Vinho branco Dão',5.49,'https://source.unsplash.com/400x400/?dao,white,wine',true,'Vinho',false,false,null),
('vn-017','continente-guarda','Lancers Rosé 75cl','Vinho rosé português',4.49,'https://source.unsplash.com/400x400/?lancers,rose',true,'Vinho',false,false,null),
('vn-018','continente-guarda','JP Azeitão Tinto 75cl','Vinho tinto Setúbal',3.99,'https://source.unsplash.com/400x400/?setubal,wine',true,'Vinho',false,false,null),
('vn-019','continente-guarda','Vinho Tinto Mesa 1L','Vinho tinto de mesa 1L',2.99,'https://source.unsplash.com/400x400/?table,wine,carafe',true,'Vinho',false,false,null),
('vn-020','continente-guarda','Vinho Branco Mesa 1L','Vinho branco de mesa 1L',2.99,'https://source.unsplash.com/400x400/?white,carafe,wine',true,'Vinho',false,false,null),
('vn-021','continente-guarda','Aliança Tinto Reserva 75cl','Vinho tinto reserva Bairrada',6.99,'https://source.unsplash.com/400x400/?bairrada,red,wine',true,'Vinho',false,false,null),
('vn-022','continente-guarda','Quinta da Aveleda 75cl','Vinho verde branco DOC',5.99,'https://source.unsplash.com/400x400/?aveleda,vinho,verde',true,'Vinho',false,false,null),
('vn-023','continente-guarda','Vinho Verde Muralhas 75cl','Vinho verde branco 75cl',4.79,'https://source.unsplash.com/400x400/?vinho,verde,bottle',true,'Vinho',false,false,null),
('vn-024','continente-guarda','Bacalhôa Tinto 75cl','Vinho tinto Setúbal premium',8.99,'https://source.unsplash.com/400x400/?bacalhoa,wine',true,'Vinho',false,false,null),
('vn-025','continente-guarda','Conde Vimioso Tinto 75cl','Vinho tinto Ribatejo',4.49,'https://source.unsplash.com/400x400/?ribatejo,red,wine',true,'Vinho',false,false,null),
('vn-026','continente-guarda','Rioja Crianza 75cl','Vinho tinto espanhol Rioja',6.99,'https://source.unsplash.com/400x400/?rioja,spanish,wine',true,'Vinho',false,false,null),
('vn-027','continente-guarda','Chianti Classico 75cl','Vinho tinto italiano Chianti',8.99,'https://source.unsplash.com/400x400/?chianti,italian,wine',true,'Vinho',false,false,null),
('vn-028','continente-guarda','Bordeaux Rouge 75cl','Vinho tinto francês Bordéus',9.49,'https://source.unsplash.com/400x400/?bordeaux,french,red',true,'Vinho',false,false,null),
('vn-029','continente-guarda','Prosecco Freixenet 75cl','Espumante italiano brut',6.99,'https://source.unsplash.com/400x400/?prosecco,sparkling',true,'Vinho',true,false,null),
('vn-030','continente-guarda','Cava Freixenet Brut 75cl','Espumante espanhol brut',5.99,'https://source.unsplash.com/400x400/?cava,freixenet',true,'Vinho',false,false,null),
('vn-031','continente-guarda','Espumante Murganheira 75cl','Espumante português Douro',7.49,'https://source.unsplash.com/400x400/?murganheira,sparkling',true,'Vinho',false,false,null),
('vn-032','continente-guarda','Moët & Chandon 75cl','Champagne francês brut',39.99,'https://source.unsplash.com/400x400/?champagne,moet',true,'Vinho',false,false,null),
('vn-033','continente-guarda','Veuve Clicquot 75cl','Champagne yellow label 75cl',49.99,'https://source.unsplash.com/400x400/?veuve,clicquot,champagne',true,'Vinho',false,false,null),
('vn-034','continente-guarda','Meia de Letes Vinho Verde 75cl','Vinho verde tinto espumante',4.99,'https://source.unsplash.com/400x400/?vinho,verde,red',true,'Vinho',false,false,null),
('vn-035','continente-guarda','Porto Ramos Pinto Tawny 75cl','Vinho do Porto tawny',12.99,'https://source.unsplash.com/400x400/?port,wine,tawny',true,'Vinho',true,false,null),
('vn-036','continente-guarda','Porto Sandeman Ruby 75cl','Vinho do Porto ruby',9.99,'https://source.unsplash.com/400x400/?sandeman,port,ruby',true,'Vinho',true,false,null),
('vn-037','continente-guarda','Porto Croft 75cl','Vinho do Porto branco',8.99,'https://source.unsplash.com/400x400/?port,white,wine',true,'Vinho',false,false,null),
('vn-038','continente-guarda','Moscatel de Setúbal 50cl','Moscatel português doce',7.99,'https://source.unsplash.com/400x400/?moscatel,sweet,wine',true,'Vinho',false,false,null),
('vn-039','continente-guarda','Vinho Tinto Bio Naturalis 75cl','Vinho tinto biológico',6.49,'https://source.unsplash.com/400x400/?organic,red,wine',true,'Vinho',false,false,null),
('vn-040','continente-guarda','Vinho Branco Bio Naturalis 75cl','Vinho branco biológico',6.49,'https://source.unsplash.com/400x400/?organic,white,wine',true,'Vinho',false,false,null),

-- ── ESPIRITUOSAS ─────────────────────────────────────────────
('es-001','continente-guarda','Jack Daniel''s 70cl','Whisky americano Tennessee 70cl',22.99,'https://source.unsplash.com/400x400/?whiskey,bourbon',true,'Espirituosas',true,false,null),
('es-002','continente-guarda','Jack Daniel''s 1L','Whisky americano Tennessee 1L',29.99,'https://source.unsplash.com/400x400/?jack,daniels,whiskey',true,'Espirituosas',true,false,null),
('es-003','continente-guarda','Jameson 70cl','Whisky irlandês 70cl',19.99,'https://source.unsplash.com/400x400/?jameson,irish,whiskey',true,'Espirituosas',true,false,null),
('es-004','continente-guarda','Johnnie Walker Red 70cl','Whisky escocês blended 70cl',18.99,'https://source.unsplash.com/400x400/?johnnie,walker,red',true,'Espirituosas',false,false,null),
('es-005','continente-guarda','Johnnie Walker Black 70cl','Whisky escocês 12 anos 70cl',29.99,'https://source.unsplash.com/400x400/?johnnie,walker,black',true,'Espirituosas',false,false,null),
('es-006','continente-guarda','Ballantine''s 70cl','Whisky escocês blended 70cl',17.99,'https://source.unsplash.com/400x400/?ballantines,scotch',true,'Espirituosas',false,false,null),
('es-007','continente-guarda','Chivas Regal 12 Anos 70cl','Whisky escocês premium 70cl',24.99,'https://source.unsplash.com/400x400/?chivas,regal,scotch',true,'Espirituosas',false,false,null),
('es-008','continente-guarda','Smirnoff Vodka 70cl','Vodka premium 37.5% 70cl',12.99,'https://source.unsplash.com/400x400/?smirnoff,vodka',true,'Espirituosas',true,false,null),
('es-009','continente-guarda','Absolut Vodka 70cl','Vodka sueca original 70cl',14.99,'https://source.unsplash.com/400x400/?absolut,vodka',true,'Espirituosas',true,false,null),
('es-010','continente-guarda','Absolut Citron 70cl','Vodka sueca limão 70cl',14.99,'https://source.unsplash.com/400x400/?absolut,lemon,vodka',true,'Espirituosas',false,false,null),
('es-011','continente-guarda','Grey Goose 70cl','Vodka francesa premium 70cl',32.99,'https://source.unsplash.com/400x400/?grey,goose,vodka',true,'Espirituosas',false,false,null),
('es-012','continente-guarda','Bombay Sapphire Gin 70cl','Gin inglês 47% 70cl',19.99,'https://source.unsplash.com/400x400/?bombay,sapphire,gin',true,'Espirituosas',true,false,null),
('es-013','continente-guarda','Tanqueray Gin 70cl','Gin inglês clássico 47.3% 70cl',18.99,'https://source.unsplash.com/400x400/?tanqueray,gin',true,'Espirituosas',false,false,null),
('es-014','continente-guarda','Hendrick''s Gin 70cl','Gin escocês premium com pepino 70cl',29.99,'https://source.unsplash.com/400x400/?hendricks,gin,cucumber',true,'Espirituosas',false,false,null),
('es-015','continente-guarda','Beefeater Gin 70cl','Gin de Londres 40% 70cl',15.99,'https://source.unsplash.com/400x400/?beefeater,london,gin',true,'Espirituosas',false,false,null),
('es-016','continente-guarda','Gordon''s Gin 70cl','Gin clássico 37.5% 70cl',13.99,'https://source.unsplash.com/400x400/?gordons,gin,classic',true,'Espirituosas',false,false,null),
('es-017','continente-guarda','Bacardi Branco 70cl','Rum branco cubano 37.5% 70cl',12.99,'https://source.unsplash.com/400x400/?bacardi,white,rum',true,'Espirituosas',true,false,null),
('es-018','continente-guarda','Captain Morgan 70cl','Rum spiced dourado 35% 70cl',14.99,'https://source.unsplash.com/400x400/?captain,morgan,rum',true,'Espirituosas',true,false,null),
('es-019','continente-guarda','Havana Club 3 Anos 70cl','Rum cubano 3 anos 40% 70cl',16.99,'https://source.unsplash.com/400x400/?havana,club,rum',true,'Espirituosas',false,false,null),
('es-020','continente-guarda','Macieira 70cl','Aguardente de vinho portuguesa 70cl',9.99,'https://source.unsplash.com/400x400/?brandy,portuguese',true,'Espirituosas',true,false,null),
('es-021','continente-guarda','Constantino 70cl','Brandy português 70cl',8.99,'https://source.unsplash.com/400x400/?constantino,brandy',true,'Espirituosas',false,false,null),
('es-022','continente-guarda','Baileys 70cl','Licor irlandês creme whisky 70cl',13.99,'https://source.unsplash.com/400x400/?baileys,cream,liqueur',true,'Espirituosas',true,false,null),
('es-023','continente-guarda','Kahlúa 70cl','Licor de café mexicano 70cl',14.99,'https://source.unsplash.com/400x400/?kahlua,coffee,liqueur',true,'Espirituosas',false,false,null),
('es-024','continente-guarda','Amaretto Disaronno 70cl','Licor de amêndoa italiano 70cl',16.99,'https://source.unsplash.com/400x400/?disaronno,amaretto',true,'Espirituosas',false,false,null),
('es-025','continente-guarda','Limoncello Luxardo 70cl','Licor de limão italiano 70cl',12.99,'https://source.unsplash.com/400x400/?limoncello,lemon,liqueur',true,'Espirituosas',false,false,null),
('es-026','continente-guarda','Aperol 70cl','Aperitivo italiano laranja 70cl',11.99,'https://source.unsplash.com/400x400/?aperol,orange,aperitif',true,'Espirituosas',true,false,null),
('es-027','continente-guarda','Campari 70cl','Aperitivo italiano amargo 70cl',13.99,'https://source.unsplash.com/400x400/?campari,italian,aperitif',true,'Espirituosas',false,false,null),
('es-028','continente-guarda','Martini Branco 75cl','Vermute branco italiano 75cl',6.99,'https://source.unsplash.com/400x400/?martini,white,vermouth',true,'Espirituosas',false,false,null),
('es-029','continente-guarda','Martini Rosso 75cl','Vermute tinto italiano 75cl',6.99,'https://source.unsplash.com/400x400/?martini,red,vermouth',true,'Espirituosas',false,false,null),
('es-030','continente-guarda','Patron Silver Tequila 70cl','Tequila mexicana premium 70cl',39.99,'https://source.unsplash.com/400x400/?patron,tequila,silver',true,'Espirituosas',false,false,null),
('es-031','continente-guarda','Jose Cuervo Gold 70cl','Tequila mexicana gold 70cl',14.99,'https://source.unsplash.com/400x400/?jose,cuervo,tequila',true,'Espirituosas',false,false,null),
('es-032','continente-guarda','Cointreau 70cl','Licor de laranja francês 70cl',17.99,'https://source.unsplash.com/400x400/?cointreau,orange,liqueur',true,'Espirituosas',false,false,null),
('es-033','continente-guarda','Malibu 70cl','Licor coco rum caribenho 70cl',12.99,'https://source.unsplash.com/400x400/?malibu,coconut,rum',true,'Espirituosas',false,false,null),
('es-034','continente-guarda','Gin Nordes Atlantic 70cl','Gin galego premium atlântico 70cl',22.99,'https://source.unsplash.com/400x400/?nordic,atlantic,gin',true,'Espirituosas',false,false,null),
('es-035','continente-guarda','Vinho do Porto LBV 75cl','Late bottled vintage port 75cl',14.99,'https://source.unsplash.com/400x400/?port,lbv,vintage',true,'Espirituosas',false,false,null),
('es-036','continente-guarda','Medronho 50cl','Aguardente de medronho algarvia 50cl',14.99,'https://source.unsplash.com/400x400/?medronho,portuguese,spirit',true,'Espirituosas',false,false,null),
('es-037','continente-guarda','Ginjinha 50cl','Licor de ginja tradicional 50cl',7.99,'https://source.unsplash.com/400x400/?ginjinha,cherry,liqueur',true,'Espirituosas',true,false,null),
('es-038','continente-guarda','Frangelico 70cl','Licor de avelã italiano 70cl',15.99,'https://source.unsplash.com/400x400/?frangelico,hazelnut',true,'Espirituosas',false,false,null),
('es-039','continente-guarda','Jägermeister 70cl','Licor herbal alemão 70cl',16.99,'https://source.unsplash.com/400x400/?jagermeister,herbal',true,'Espirituosas',false,false,null),
('es-040','continente-guarda','Fireball Whisky 70cl','Whisky canela 33% 70cl',12.99,'https://source.unsplash.com/400x400/?fireball,cinnamon,whisky',true,'Espirituosas',false,false,null),

-- ── CAFÉ ─────────────────────────────────────────────────────
('ca-001','continente-guarda','Delta Café Superior 250g','Café torrado moído superior',2.99,'https://source.unsplash.com/400x400/?coffee,ground',true,'Café',true,false,null),
('ca-002','continente-guarda','Delta Café Superior 500g','Café torrado moído superior 500g',5.49,'https://source.unsplash.com/400x400/?coffee,bag',true,'Café',true,false,null),
('ca-003','continente-guarda','Delta Café Gold 250g','Café torrado moído premium',3.49,'https://source.unsplash.com/400x400/?coffee,premium,gold',true,'Café',false,false,null),
('ca-004','continente-guarda','Delta Café Grão 250g','Café em grão torrado 250g',3.49,'https://source.unsplash.com/400x400/?coffee,beans',true,'Café',false,false,null),
('ca-005','continente-guarda','Nicola Café Moka 250g','Café moído para bule 250g',2.79,'https://source.unsplash.com/400x400/?nicola,coffee',true,'Café',true,false,null),
('ca-006','continente-guarda','Nicola Café Clássico 500g','Café torrado clássico 500g',4.99,'https://source.unsplash.com/400x400/?classic,coffee,bag',true,'Café',false,false,null),
('ca-007','continente-guarda','Sical 5 Estrelas 250g','Café torrado moído 250g',2.49,'https://source.unsplash.com/400x400/?sical,coffee,five',true,'Café',true,false,null),
('ca-008','continente-guarda','Sical 5 Estrelas 500g','Café torrado moído 500g',4.49,'https://source.unsplash.com/400x400/?sical,coffee,stars',true,'Café',false,false,null),
('ca-009','continente-guarda','Buondi Café 250g','Café moído torrado 250g',2.69,'https://source.unsplash.com/400x400/?buondi,coffee',true,'Café',false,false,null),
('ca-010','continente-guarda','Nescafé Clássico 200g','Café solúvel clássico 200g',5.49,'https://source.unsplash.com/400x400/?nescafe,instant,coffee',true,'Café',true,false,null),
('ca-011','continente-guarda','Nescafé Gold 200g','Café solúvel premium 200g',6.99,'https://source.unsplash.com/400x400/?nescafe,gold,coffee',true,'Café',false,false,null),
('ca-012','continente-guarda','Nescafé Dolce Gusto Americano 16 cápsulas','Cápsulas café americano',5.99,'https://source.unsplash.com/400x400/?dolce,gusto,capsule',true,'Café',true,false,null),
('ca-013','continente-guarda','Nescafé Dolce Gusto Espresso 16 cápsulas','Cápsulas café espresso',5.99,'https://source.unsplash.com/400x400/?espresso,capsule,coffee',true,'Café',true,false,null),
('ca-014','continente-guarda','Nescafé Dolce Gusto Cappuccino 8 cápsulas','Cápsulas cappuccino',5.99,'https://source.unsplash.com/400x400/?cappuccino,capsule',true,'Café',false,false,null),
('ca-015','continente-guarda','Nescafé Dolce Gusto Latte 8 cápsulas','Cápsulas latte macchiato',5.99,'https://source.unsplash.com/400x400/?latte,capsule,coffee',true,'Café',false,false,null),
('ca-016','continente-guarda','L''Or Espresso 10 cápsulas Nespresso','Cápsulas espresso compatível Nespresso',3.99,'https://source.unsplash.com/400x400/?nespresso,capsule',true,'Café',true,false,null),
('ca-017','continente-guarda','Delta Q 10 cápsulas Espresso','Cápsulas espresso Delta Q',3.99,'https://source.unsplash.com/400x400/?delta,q,capsule',true,'Café',true,false,null),
('ca-018','continente-guarda','Delta Q Pack 40 cápsulas','Pack cápsulas café 40 un',14.99,'https://source.unsplash.com/400x400/?coffee,capsule,pack',true,'Café',false,false,null),
('ca-019','continente-guarda','Segafredo Zanetti 250g','Café italiano torrado moído',3.29,'https://source.unsplash.com/400x400/?segafredo,italian,coffee',true,'Café',false,false,null),
('ca-020','continente-guarda','Illy Caffè 250g','Café italiano premium moído',7.99,'https://source.unsplash.com/400x400/?illy,coffee,premium',true,'Café',false,false,null),
('ca-021','continente-guarda','Lavazza Crema e Gusto 250g','Café italiano crema e gusto 250g',3.49,'https://source.unsplash.com/400x400/?lavazza,coffee,italian',true,'Café',false,false,null),
('ca-022','continente-guarda','Nescafé 3 em 1 Original 10 saquetas','Café solúvel com leite e açúcar',2.99,'https://source.unsplash.com/400x400/?coffee,three,in,one',true,'Café',true,false,null),
('ca-023','continente-guarda','Nescafé 3 em 1 Forte 10 saquetas','Café forte solúvel com leite 10 saq.',2.99,'https://source.unsplash.com/400x400/?strong,coffee,sachet',true,'Café',false,false,null),
('ca-024','continente-guarda','Maxim Café Torrado 250g','Café torrado moído económico',1.99,'https://source.unsplash.com/400x400/?coffee,economy',true,'Café',false,false,null),
('ca-025','continente-guarda','Café Torrado Continente 250g','Café moído marca própria 250g',1.49,'https://source.unsplash.com/400x400/?own,brand,coffee',true,'Café',false,false,null),
('ca-026','continente-guarda','Café Descafeinado Delta 250g','Café descafeinado moído 250g',3.29,'https://source.unsplash.com/400x400/?decaf,coffee',true,'Café',false,false,null),
('ca-027','continente-guarda','Nescafé Descafeinado 200g','Café solúvel descafeinado 200g',5.99,'https://source.unsplash.com/400x400/?decaffeinated,instant',true,'Café',false,false,null),
('ca-028','continente-guarda','Café Orgânico Bio Delta 250g','Café orgânico biológico 250g',4.49,'https://source.unsplash.com/400x400/?organic,coffee,bio',true,'Café',false,false,null),

-- ── CHÁ E INFUSÕES ───────────────────────────────────────────
('te-001','continente-guarda','Lipton Chá Preto 25 saquetas','Chá preto clássico 25 saquetas',1.99,'https://source.unsplash.com/400x400/?black,tea,bags',true,'Chá e Infusões',true,false,null),
('te-002','continente-guarda','Lipton Chá Verde 25 saquetas','Chá verde natural 25 saquetas',1.99,'https://source.unsplash.com/400x400/?green,tea,bag',true,'Chá e Infusões',true,false,null),
('te-003','continente-guarda','Twinings Earl Grey 25 saquetas','Chá preto com bergamota 25 saquetas',2.99,'https://source.unsplash.com/400x400/?earl,grey,tea',true,'Chá e Infusões',true,false,null),
('te-004','continente-guarda','Twinings English Breakfast 25 saquetas','Chá preto forte britânico',2.99,'https://source.unsplash.com/400x400/?english,breakfast,tea',true,'Chá e Infusões',false,false,null),
('te-005','continente-guarda','Twinings Camomila 20 saquetas','Infusão de camomila relaxante',2.79,'https://source.unsplash.com/400x400/?chamomile,tea',true,'Chá e Infusões',true,false,null),
('te-006','continente-guarda','Twinings Hortelã-Pimenta 20 saquetas','Infusão hortelã pimenta digestiva',2.79,'https://source.unsplash.com/400x400/?peppermint,tea',true,'Chá e Infusões',false,false,null),
('te-007','continente-guarda','Twinings Frutos Vermelhos 20 saquetas','Infusão frutos vermelhos',2.79,'https://source.unsplash.com/400x400/?berries,tea,red',true,'Chá e Infusões',false,false,null),
('te-008','continente-guarda','Twinings Gengibre Limão 20 saquetas','Infusão gengibre e limão',2.79,'https://source.unsplash.com/400x400/?ginger,lemon,tea',true,'Chá e Infusões',false,false,null),
('te-009','continente-guarda','Tisane Tília 20 saquetas','Infusão de tília calmante',1.49,'https://source.unsplash.com/400x400/?linden,herbal,tea',true,'Chá e Infusões',false,false,null),
('te-010','continente-guarda','Tisane Erva-Cidreira 20 saquetas','Infusão erva-cidreira relaxante',1.49,'https://source.unsplash.com/400x400/?lemon,balm,tea',true,'Chá e Infusões',false,false,null),
('te-011','continente-guarda','Tisane Melissa 20 saquetas','Infusão melissa e hortelã',1.49,'https://source.unsplash.com/400x400/?melissa,herbal',true,'Chá e Infusões',false,false,null),
('te-012','continente-guarda','Celestial Sleepytime 20 saquetas','Infusão para dormir camomila',3.49,'https://source.unsplash.com/400x400/?sleep,herbal,tea',true,'Chá e Infusões',false,false,null),
('te-013','continente-guarda','Chá Verde Matcha 30g','Pó de matcha japonês premium',5.99,'https://source.unsplash.com/400x400/?matcha,green,powder',true,'Chá e Infusões',false,false,null),
('te-014','continente-guarda','Chá Rooibos 20 saquetas','Infusão rooibos sul-africana',2.49,'https://source.unsplash.com/400x400/?rooibos,red,tea',true,'Chá e Infusões',false,false,null),
('te-015','continente-guarda','Chá Preto Continente 25 saquetas','Chá preto marca própria',0.89,'https://source.unsplash.com/400x400/?tea,economy,bag',true,'Chá e Infusões',false,false,null),
('te-016','continente-guarda','Ahmad Tea Earl Grey 100g','Chá earl grey folha solta 100g',4.99,'https://source.unsplash.com/400x400/?loose,leaf,tea',true,'Chá e Infusões',false,false,null),
('te-017','continente-guarda','Chá Verde Jasmin 20 saquetas','Chá verde com flores de jasmin',2.49,'https://source.unsplash.com/400x400/?jasmine,green,tea',true,'Chá e Infusões',false,false,null),
('te-018','continente-guarda','Infusão Equinácea 20 saquetas','Infusão equinácea defesas naturais',3.29,'https://source.unsplash.com/400x400/?echinacea,immunity,tea',true,'Chá e Infusões',false,false,null),
('te-019','continente-guarda','Chá Branco 20 saquetas','Chá branco delicado e suave',3.49,'https://source.unsplash.com/400x400/?white,tea,delicate',true,'Chá e Infusões',false,false,null),
('te-020','continente-guarda','Infusão Alcaçuz 20 saquetas','Infusão de alcaçuz digestiva',1.99,'https://source.unsplash.com/400x400/?licorice,herbal,infusion',true,'Chá e Infusões',false,false,null),

-- ── CEREAIS ──────────────────────────────────────────────────
('ce-001','continente-guarda','Kellogg''s Corn Flakes 500g','Flocos de milho clássicos 500g',3.49,'https://source.unsplash.com/400x400/?cornflakes,cereal',true,'Cereais',true,false,null),
('ce-002','continente-guarda','Kellogg''s Special K 375g','Cereais light com arroz e trigo',3.99,'https://source.unsplash.com/400x400/?special,k,cereal',true,'Cereais',true,false,null),
('ce-003','continente-guarda','Nestlé Chocapic 430g','Cereais de chocolate para crianças',3.49,'https://source.unsplash.com/400x400/?chocapic,chocolate,cereal',true,'Cereais',true,false,null),
('ce-004','continente-guarda','Nestlé Estrelitas 430g','Cereais estrelinha de milho 430g',3.49,'https://source.unsplash.com/400x400/?star,cereal,kids',true,'Cereais',false,false,null),
('ce-005','continente-guarda','Nestlé Cini Minis 350g','Cereais canela mini 350g',3.49,'https://source.unsplash.com/400x400/?cinnamon,cereal,mini',true,'Cereais',false,false,null),
('ce-006','continente-guarda','Nestlé Cheerios 375g','Cereais integrais de aveia 375g',3.29,'https://source.unsplash.com/400x400/?cheerios,oat,cereal',true,'Cereais',false,false,null),
('ce-007','continente-guarda','Kellogg''s Frosties 500g','Flocos de milho com açúcar 500g',3.49,'https://source.unsplash.com/400x400/?frosties,sweet,cereal',true,'Cereais',false,false,null),
('ce-008','continente-guarda','Weetabix 24 biscoitos','Biscoitos de trigo integral 430g',3.29,'https://source.unsplash.com/400x400/?weetabix,wheat,biscuit',true,'Cereais',false,false,null),
('ce-009','continente-guarda','Muesli Clássico Jordans 500g','Muesli com frutos secos 500g',4.49,'https://source.unsplash.com/400x400/?muesli,oats,fruits',true,'Cereais',false,false,null),
('ce-010','continente-guarda','Granola Mel e Nozes 500g','Granola crocante mel e nozes',3.99,'https://source.unsplash.com/400x400/?granola,honey,nuts',true,'Cereais',true,false,null),
('ce-011','continente-guarda','Granola Frutos Vermelhos 450g','Granola com frutos vermelhos',3.99,'https://source.unsplash.com/400x400/?granola,berries,red',true,'Cereais',false,false,null),
('ce-012','continente-guarda','Flocos de Aveia 500g','Aveia flocos integrais 500g',1.29,'https://source.unsplash.com/400x400/?oats,flakes,healthy',true,'Cereais',true,false,null),
('ce-013','continente-guarda','Flocos de Aveia 1kg','Aveia flocos integrais 1kg',2.29,'https://source.unsplash.com/400x400/?oatmeal,bowl,healthy',true,'Cereais',false,false,null),
('ce-014','continente-guarda','Kellogg''s Crunchy Nut 500g','Flocos milho com mel e amendoins',3.99,'https://source.unsplash.com/400x400/?crunchy,nut,cereal',true,'Cereais',false,false,null),
('ce-015','continente-guarda','Nestlé Shreddies 500g','Cereais trigo integral 500g',3.29,'https://source.unsplash.com/400x400/?shreddies,wheat,cereal',true,'Cereais',false,false,null),
('ce-016','continente-guarda','Lucky Charms 300g','Cereais mágicos americanos 300g',4.99,'https://source.unsplash.com/400x400/?lucky,charms,marshmallow',true,'Cereais',false,false,null),
('ce-017','continente-guarda','Cereais Musli Bio 500g','Muesli biológico sem açúcar 500g',4.49,'https://source.unsplash.com/400x400/?bio,muesli,organic',true,'Cereais',false,false,null),
('ce-018','continente-guarda','Fitness Nestlé 375g','Cereais fitness com vitaminas',3.49,'https://source.unsplash.com/400x400/?fitness,cereal,health',true,'Cereais',false,false,null),
('ce-019','continente-guarda','Kellogg''s All-Bran 500g','Cereais muito ricos em fibra',3.79,'https://source.unsplash.com/400x400/?bran,fiber,cereal',true,'Cereais',false,false,null),
('ce-020','continente-guarda','Cereais Continente 500g','Flocos milho marca própria',1.19,'https://source.unsplash.com/400x400/?cereal,economy,flakes',true,'Cereais',false,false,null),

-- ── BOLACHAS ─────────────────────────────────────────────────
('bl-001','continente-guarda','Bolachas Maria Continente 400g','Bolachas maria clássicas 400g',0.79,'https://source.unsplash.com/400x400/?maria,biscuit,cookie',true,'Bolachas e Biscoitos',true,false,null),
('bl-002','continente-guarda','Bolachas Maria LU 400g','Bolachas maria LU 400g',1.29,'https://source.unsplash.com/400x400/?lu,maria,biscuit',true,'Bolachas e Biscoitos',true,false,null),
('bl-003','continente-guarda','Bolachas Água e Sal 200g','Bolachas clássicas água e sal',0.69,'https://source.unsplash.com/400x400/?water,salt,cracker',true,'Bolachas e Biscoitos',true,false,null),
('bl-004','continente-guarda','McVitie''s Digestive 400g','Bolachas digestivas clássicas',1.99,'https://source.unsplash.com/400x400/?digestive,biscuit',true,'Bolachas e Biscoitos',true,false,null),
('bl-005','continente-guarda','McVitie''s Digestive Chocolate 300g','Digestivas com chocolate de leite',2.29,'https://source.unsplash.com/400x400/?chocolate,digestive',true,'Bolachas e Biscoitos',true,false,null),
('bl-006','continente-guarda','Oreo Clássico 154g','Bolachas recheio baunilha 154g',1.49,'https://source.unsplash.com/400x400/?oreo,cookies,cream',true,'Bolachas e Biscoitos',true,false,null),
('bl-007','continente-guarda','Oreo Double Cream 157g','Oreo duplo recheio 157g',1.79,'https://source.unsplash.com/400x400/?oreo,double,cream',true,'Bolachas e Biscoitos',false,false,null),
('bl-008','continente-guarda','Oreo Chocolate 154g','Oreo com cacau 154g',1.49,'https://source.unsplash.com/400x400/?oreo,chocolate,cookie',true,'Bolachas e Biscoitos',false,false,null),
('bl-009','continente-guarda','Ritz Clássico 200g','Bolachas salgadas amanteigadas',1.99,'https://source.unsplash.com/400x400/?ritz,cracker,salty',true,'Bolachas e Biscoitos',true,false,null),
('bl-010','continente-guarda','Ritz Queijo 200g','Bolachas salgadas com queijo',2.09,'https://source.unsplash.com/400x400/?ritz,cheese,cracker',true,'Bolachas e Biscoitos',false,false,null),
('bl-011','continente-guarda','Chips Ahoy! Clássico 128g','Bolachas com pepitas de chocolate',1.89,'https://source.unsplash.com/400x400/?chips,ahoy,chocolate,chip',true,'Bolachas e Biscoitos',false,false,null),
('bl-012','continente-guarda','Kit Kat Original 41.5g','Wafer chocolate de leite',0.89,'https://source.unsplash.com/400x400/?kitkat,wafer,chocolate',true,'Bolachas e Biscoitos',true,false,null),
('bl-013','continente-guarda','Kit Kat Chunky 40g','Kit Kat espesso chocolate de leite',0.99,'https://source.unsplash.com/400x400/?kitkat,chunky',true,'Bolachas e Biscoitos',false,false,null),
('bl-014','continente-guarda','Bolacha Torrada Continente 300g','Bolacha torrada clássica',0.89,'https://source.unsplash.com/400x400/?toast,biscuit,brown',true,'Bolachas e Biscoitos',false,false,null),
('bl-015','continente-guarda','Palitos La Reine 200g','Palitos de champanhe 200g',1.29,'https://source.unsplash.com/400x400/?ladyfinger,biscuit',true,'Bolachas e Biscoitos',false,false,null),
('bl-016','continente-guarda','Crackers Integral 250g','Crackers integrais fibra alta',1.49,'https://source.unsplash.com/400x400/?wholegrain,cracker',true,'Bolachas e Biscoitos',false,false,null),
('bl-017','continente-guarda','Digestive Canela 300g','Bolachas digestivas com canela',1.89,'https://source.unsplash.com/400x400/?cinnamon,digestive,biscuit',true,'Bolachas e Biscoitos',false,false,null),
('bl-018','continente-guarda','Príncipe Chocolate 300g','Bolachas recheadas chocolate',1.19,'https://source.unsplash.com/400x400/?prince,chocolate,biscuit',true,'Bolachas e Biscoitos',true,false,null),
('bl-019','continente-guarda','LU Pim''s Laranja 150g','Bolachas biscoito laranja',2.49,'https://source.unsplash.com/400x400/?pims,orange,biscuit',true,'Bolachas e Biscoitos',false,false,null),
('bl-020','continente-guarda','Gullon Digestive 400g','Bolachas digestivas sem açúcar',2.29,'https://source.unsplash.com/400x400/?gullon,digestive,sugarfree',true,'Bolachas e Biscoitos',false,false,null),
('bl-021','continente-guarda','Wasa Crispbread 275g','Torradas escandinavas de centeio',2.49,'https://source.unsplash.com/400x400/?wasa,rye,crispbread',true,'Bolachas e Biscoitos',false,false,null),
('bl-022','continente-guarda','Bolachas Amaretti 200g','Bolachas amêndoa italianas',3.29,'https://source.unsplash.com/400x400/?amaretti,almond,italian',true,'Bolachas e Biscoitos',false,false,null),
('bl-023','continente-guarda','Papadums 100g','Crackers indianos finos',1.49,'https://source.unsplash.com/400x400/?papadum,indian,cracker',true,'Bolachas e Biscoitos',false,false,null),
('bl-024','continente-guarda','Bolacha Champanhe 100g','Bolachas levedo para sobremesa',0.99,'https://source.unsplash.com/400x400/?savardii,biscuit',true,'Bolachas e Biscoitos',false,false,null),
('bl-025','continente-guarda','Tosta Rica Original 570g','Torradas finas crocantes 570g',2.49,'https://source.unsplash.com/400x400/?toast,thin,cracker',true,'Bolachas e Biscoitos',true,false,null),
('bl-026','continente-guarda','Tosta Rica Integral 570g','Torradas integrais finas',2.49,'https://source.unsplash.com/400x400/?wholemeal,toast,thin',true,'Bolachas e Biscoitos',false,false,null),
('bl-027','continente-guarda','Belvita Mel e Nozes 50g','Bolachas pequeno almoço',0.99,'https://source.unsplash.com/400x400/?belvita,breakfast,honey',true,'Bolachas e Biscoitos',false,false,null),
('bl-028','continente-guarda','Belvita Mirtilo 50g','Bolachas pequeno almoço mirtilo',0.99,'https://source.unsplash.com/400x400/?belvita,blueberry',true,'Bolachas e Biscoitos',false,false,null),
('bl-029','continente-guarda','Biscoito Amanteigado 300g','Biscoito amanteigado português',1.29,'https://source.unsplash.com/400x400/?butter,biscuit,shortbread',true,'Bolachas e Biscoitos',false,false,null),
('bl-030','continente-guarda','Shortbread Walkers 150g','Shortbread escocês premium',2.99,'https://source.unsplash.com/400x400/?walkers,shortbread,scottish',true,'Bolachas e Biscoitos',false,false,null)

ON CONFLICT (id) DO NOTHING;
