-- ============================================================
-- BORA APP — EXPANSÃO CATÁLOGO PARTE 1/4
-- Refrigerantes · Água · Ice Tea · Cerveja
-- ============================================================

INSERT INTO public.products
  (id, restaurant_id, name, description, price, photo_url, is_available, category, is_popular, is_on_sale, discount_price)
VALUES

-- ── REFRIGERANTES ───────────────────────────────────────────
('bv-001','continente-guarda','Coca-Cola 33cl','Refrigerante clássico lata 33cl',0.99,'https://source.unsplash.com/400x400/?coca-cola,soda',true,'Refrigerantes',true,false,null),
('bv-002','continente-guarda','Coca-Cola 1L','Refrigerante clássico garrafa 1L',1.79,'https://source.unsplash.com/400x400/?cola,bottle',true,'Refrigerantes',true,false,null),
('bv-003','continente-guarda','Coca-Cola 1.5L','Refrigerante clássico garrafa 1.5L',1.99,'https://source.unsplash.com/400x400/?cola,beverage',true,'Refrigerantes',true,false,null),
('bv-004','continente-guarda','Coca-Cola 2L','Refrigerante clássico garrafa 2L',2.29,'https://source.unsplash.com/400x400/?soda,cola',true,'Refrigerantes',true,false,null),
('bv-005','continente-guarda','Coca-Cola Zero 33cl','Sem açúcar lata 33cl',0.99,'https://source.unsplash.com/400x400/?diet,cola',true,'Refrigerantes',true,false,null),
('bv-006','continente-guarda','Coca-Cola Zero 1.5L','Sem açúcar garrafa 1.5L',1.99,'https://source.unsplash.com/400x400/?zero,soda',true,'Refrigerantes',true,false,null),
('bv-007','continente-guarda','Coca-Cola Zero 2L','Sem açúcar garrafa 2L',2.29,'https://source.unsplash.com/400x400/?zero,cola',true,'Refrigerantes',false,false,null),
('bv-008','continente-guarda','Coca-Cola Light 33cl','Light lata 33cl',0.99,'https://source.unsplash.com/400x400/?light,drink',true,'Refrigerantes',false,false,null),
('bv-009','continente-guarda','Pepsi 33cl','Refrigerante cola lata 33cl',0.89,'https://source.unsplash.com/400x400/?pepsi,soda',true,'Refrigerantes',true,false,null),
('bv-010','continente-guarda','Pepsi 1.5L','Refrigerante cola garrafa 1.5L',1.79,'https://source.unsplash.com/400x400/?pepsi,bottle',true,'Refrigerantes',false,false,null),
('bv-011','continente-guarda','Pepsi 2L','Refrigerante cola garrafa 2L',2.09,'https://source.unsplash.com/400x400/?pepsi,large',true,'Refrigerantes',false,false,null),
('bv-012','continente-guarda','Pepsi Max 33cl','Sem açúcar lata 33cl',0.89,'https://source.unsplash.com/400x400/?pepsi,max',true,'Refrigerantes',false,false,null),
('bv-013','continente-guarda','Pepsi Max 1.5L','Sem açúcar garrafa 1.5L',1.79,'https://source.unsplash.com/400x400/?max,diet',true,'Refrigerantes',false,false,null),
('bv-014','continente-guarda','7UP 33cl','Refrigerante limão-lima lata 33cl',0.89,'https://source.unsplash.com/400x400/?7up,lemon',true,'Refrigerantes',false,false,null),
('bv-015','continente-guarda','7UP 1.5L','Refrigerante limão-lima garrafa 1.5L',1.79,'https://source.unsplash.com/400x400/?7up,lime',true,'Refrigerantes',false,false,null),
('bv-016','continente-guarda','Fanta Laranja 33cl','Refrigerante laranja lata 33cl',0.99,'https://source.unsplash.com/400x400/?fanta,orange',true,'Refrigerantes',true,false,null),
('bv-017','continente-guarda','Fanta Laranja 1.5L','Refrigerante laranja garrafa 1.5L',1.99,'https://source.unsplash.com/400x400/?orange,soda',true,'Refrigerantes',true,false,null),
('bv-018','continente-guarda','Fanta Laranja 2L','Refrigerante laranja garrafa 2L',2.29,'https://source.unsplash.com/400x400/?orange,drink',true,'Refrigerantes',false,false,null),
('bv-019','continente-guarda','Fanta Limão 33cl','Refrigerante limão lata 33cl',0.99,'https://source.unsplash.com/400x400/?lemon,soda',true,'Refrigerantes',false,false,null),
('bv-020','continente-guarda','Fanta Limão 1.5L','Refrigerante limão garrafa 1.5L',1.99,'https://source.unsplash.com/400x400/?lemon,drink',true,'Refrigerantes',false,false,null),
('bv-021','continente-guarda','Fanta Morango 33cl','Refrigerante morango lata 33cl',0.99,'https://source.unsplash.com/400x400/?strawberry,soda',true,'Refrigerantes',false,false,null),
('bv-022','continente-guarda','Sprite 33cl','Refrigerante limão-lima lata 33cl',0.99,'https://source.unsplash.com/400x400/?sprite,green',true,'Refrigerantes',true,false,null),
('bv-023','continente-guarda','Sprite 1.5L','Refrigerante limão-lima garrafa 1.5L',1.99,'https://source.unsplash.com/400x400/?sprite,bottle',true,'Refrigerantes',false,false,null),
('bv-024','continente-guarda','Sumol Laranja 33cl','Sumo laranja com gás lata 33cl',0.89,'https://source.unsplash.com/400x400/?orange,fizzy',true,'Refrigerantes',true,false,null),
('bv-025','continente-guarda','Sumol Laranja 1.5L','Sumo laranja com gás garrafa 1.5L',1.79,'https://source.unsplash.com/400x400/?orange,carbonated',true,'Refrigerantes',true,false,null),
('bv-026','continente-guarda','Sumol Pêssego 33cl','Sumo pêssego com gás lata 33cl',0.89,'https://source.unsplash.com/400x400/?peach,soda',true,'Refrigerantes',false,false,null),
('bv-027','continente-guarda','Sumol Ananás 33cl','Sumo ananás com gás lata 33cl',0.89,'https://source.unsplash.com/400x400/?pineapple,drink',true,'Refrigerantes',false,false,null),
('bv-028','continente-guarda','Schweppes Tónica 20cl','Água tónica clássica 20cl',0.69,'https://source.unsplash.com/400x400/?tonic,water',true,'Refrigerantes',true,false,null),
('bv-029','continente-guarda','Schweppes Tónica 1L','Água tónica clássica 1L',1.49,'https://source.unsplash.com/400x400/?tonic,bottle',true,'Refrigerantes',false,false,null),
('bv-030','continente-guarda','Schweppes Limão 20cl','Limonada com gás 20cl',0.69,'https://source.unsplash.com/400x400/?lemon,tonic',true,'Refrigerantes',false,false,null),
('bv-031','continente-guarda','Schweppes Ginger Ale 20cl','Ginger ale com gás 20cl',0.69,'https://source.unsplash.com/400x400/?ginger,ale',true,'Refrigerantes',false,false,null),
('bv-032','continente-guarda','Red Bull 25cl','Bebida energética clássica 25cl',1.79,'https://source.unsplash.com/400x400/?energy,drink',true,'Refrigerantes',true,false,null),
('bv-033','continente-guarda','Red Bull Zero 25cl','Bebida energética sem açúcar 25cl',1.79,'https://source.unsplash.com/400x400/?energy,zero',true,'Refrigerantes',false,false,null),
('bv-034','continente-guarda','Red Bull Pack 4x25cl','Pack energético 4x25cl',5.99,'https://source.unsplash.com/400x400/?energy,pack',true,'Refrigerantes',true,false,null),
('bv-035','continente-guarda','Monster Energy 50cl','Bebida energética original 50cl',1.89,'https://source.unsplash.com/400x400/?monster,energy',true,'Refrigerantes',true,false,null),
('bv-036','continente-guarda','Monster Zero 50cl','Bebida energética zero açúcar 50cl',1.89,'https://source.unsplash.com/400x400/?monster,zero',true,'Refrigerantes',false,false,null),
('bv-037','continente-guarda','Monster Mango 50cl','Bebida energética manga 50cl',1.89,'https://source.unsplash.com/400x400/?mango,energy',true,'Refrigerantes',false,false,null),
('bv-038','continente-guarda','Gatorade Azul 50cl','Bebida isotónica azul 50cl',1.49,'https://source.unsplash.com/400x400/?sports,drink',true,'Refrigerantes',false,false,null),
('bv-039','continente-guarda','Gatorade Laranja 50cl','Bebida isotónica laranja 50cl',1.49,'https://source.unsplash.com/400x400/?gatorade,orange',true,'Refrigerantes',false,false,null),
('bv-040','continente-guarda','Powerade Azul 500ml','Bebida isotónica azul 500ml',1.39,'https://source.unsplash.com/400x400/?powerade,sports',true,'Refrigerantes',false,false,null),
('bv-041','continente-guarda','Powerade Morango 500ml','Bebida isotónica morango 500ml',1.39,'https://source.unsplash.com/400x400/?sports,strawberry',true,'Refrigerantes',false,false,null),
('bv-042','continente-guarda','Frize Limão 33cl','Refrigerante limão com gás 33cl',0.79,'https://source.unsplash.com/400x400/?lemon,sparkling',true,'Refrigerantes',false,false,null),
('bv-043','continente-guarda','Frize Pêssego 33cl','Refrigerante pêssego com gás 33cl',0.79,'https://source.unsplash.com/400x400/?peach,sparkling',true,'Refrigerantes',false,false,null),
('bv-044','continente-guarda','Guaraná Antarctica 35cl','Refrigerante guaraná brasileiro 35cl',0.89,'https://source.unsplash.com/400x400/?guarana,brazilian',true,'Refrigerantes',false,false,null),
('bv-045','continente-guarda','Bom Dia Laranja 1.5L','Refrigerante laranja 1.5L',1.29,'https://source.unsplash.com/400x400/?orange,refreshment',true,'Refrigerantes',false,false,null),
('bv-046','continente-guarda','Bom Dia Pêssego 1.5L','Refrigerante pêssego 1.5L',1.29,'https://source.unsplash.com/400x400/?peach,drink',true,'Refrigerantes',false,false,null),
('bv-047','continente-guarda','Bom Dia Ananás 1.5L','Refrigerante ananás 1.5L',1.29,'https://source.unsplash.com/400x400/?pineapple,fizz',true,'Refrigerantes',false,false,null),
('bv-048','continente-guarda','Nestlé Nesquik 200ml','Leite com chocolate 200ml',0.79,'https://source.unsplash.com/400x400/?chocolate,milk',true,'Refrigerantes',true,false,null),
('bv-049','continente-guarda','Compal Clássico Laranja 200ml','Sumo laranja com polpa 200ml',0.69,'https://source.unsplash.com/400x400/?orange,juice',true,'Refrigerantes',false,false,null),
('bv-050','continente-guarda','Compal Clássico Laranja 1L','Sumo laranja com polpa 1L',1.49,'https://source.unsplash.com/400x400/?orange,classic',true,'Refrigerantes',true,false,null),
('bv-051','continente-guarda','Aquarius Limão 50cl','Bebida isotónica limão 50cl',1.19,'https://source.unsplash.com/400x400/?aquarius,lemon',true,'Refrigerantes',false,false,null),
('bv-052','continente-guarda','Aquarius Ananás 50cl','Bebida isotónica ananás 50cl',1.19,'https://source.unsplash.com/400x400/?aquarius,pineapple',true,'Refrigerantes',false,false,null),
('bv-053','continente-guarda','Coca-Cola Pack 6x33cl','Pack cola 6 latas 33cl',4.99,'https://source.unsplash.com/400x400/?cola,pack',true,'Refrigerantes',true,false,null),
('bv-054','continente-guarda','Fanta Pack 6x33cl','Pack fanta laranja 6 latas',4.79,'https://source.unsplash.com/400x400/?fanta,pack',true,'Refrigerantes',false,false,null),
('bv-055','continente-guarda','Burn Energy 25cl','Bebida energética 25cl',1.49,'https://source.unsplash.com/400x400/?burn,energy',true,'Refrigerantes',false,false,null),
('bv-056','continente-guarda','Vitamin Well Tropical 50cl','Bebida vitaminada tropical 50cl',1.89,'https://source.unsplash.com/400x400/?vitamin,drink',true,'Refrigerantes',false,false,null),
('bv-057','continente-guarda','Vitamin Well Defence 50cl','Bebida vitaminada defesa 50cl',1.89,'https://source.unsplash.com/400x400/?vitamin,water',true,'Refrigerantes',false,false,null),
('bv-058','continente-guarda','Tropicana Laranja 850ml','Sumo laranja premium 850ml',2.49,'https://source.unsplash.com/400x400/?tropicana,orange',true,'Refrigerantes',false,false,null),
('bv-059','continente-guarda','Santal Laranja 1L','Sumo laranja néctar 1L',1.19,'https://source.unsplash.com/400x400/?santal,juice',true,'Refrigerantes',false,false,null),
('bv-060','continente-guarda','Sprite Zero 33cl','Sem açúcar limão-lima lata 33cl',0.99,'https://source.unsplash.com/400x400/?sprite,zero',true,'Refrigerantes',false,false,null),

-- ── ÁGUA ────────────────────────────────────────────────────
('ag-001','continente-guarda','Luso Natural 33cl','Água mineral natural 33cl',0.35,'https://source.unsplash.com/400x400/?water,bottle',true,'Água',true,false,null),
('ag-002','continente-guarda','Luso Natural 50cl','Água mineral natural 50cl',0.45,'https://source.unsplash.com/400x400/?water,mineral',true,'Água',true,false,null),
('ag-003','continente-guarda','Luso Natural 1.5L','Água mineral natural 1.5L',0.59,'https://source.unsplash.com/400x400/?luso,water',true,'Água',true,false,null),
('ag-004','continente-guarda','Luso Natural 5L','Água mineral natural 5L',1.49,'https://source.unsplash.com/400x400/?water,large',true,'Água',true,false,null),
('ag-005','continente-guarda','Luso 6x1.5L','Pack água mineral 6 garrafas',2.99,'https://source.unsplash.com/400x400/?water,pack',true,'Água',true,true,2.49),
('ag-006','continente-guarda','Luso 24x33cl','Pack água mineral 24 garrafinhas',5.99,'https://source.unsplash.com/400x400/?water,multipack',true,'Água',true,false,null),
('ag-007','continente-guarda','Luso com Gás 75cl','Água com gás garrafa 75cl',0.89,'https://source.unsplash.com/400x400/?sparkling,water',true,'Água',true,false,null),
('ag-008','continente-guarda','Luso com Gás 33cl','Água com gás garrafa 33cl',0.49,'https://source.unsplash.com/400x400/?sparkling,bottle',true,'Água',false,false,null),
('ag-009','continente-guarda','Pedras Natural com Gás 75cl','Água natural com gás 75cl',1.19,'https://source.unsplash.com/400x400/?carbonated,water',true,'Água',true,false,null),
('ag-010','continente-guarda','Pedras Limão 33cl','Água com gás e limão 33cl',0.79,'https://source.unsplash.com/400x400/?lemon,water',true,'Água',false,false,null),
('ag-011','continente-guarda','Pedras Menta 33cl','Água com gás e menta 33cl',0.79,'https://source.unsplash.com/400x400/?mint,water',true,'Água',false,false,null),
('ag-012','continente-guarda','Vitalis Natural 33cl','Água mineral natural 33cl',0.35,'https://source.unsplash.com/400x400/?mineral,water',true,'Água',false,false,null),
('ag-013','continente-guarda','Vitalis Natural 1.5L','Água mineral natural 1.5L',0.55,'https://source.unsplash.com/400x400/?vitalis,water',true,'Água',false,false,null),
('ag-014','continente-guarda','Vitalis Natural 5L','Água mineral natural 5L',1.29,'https://source.unsplash.com/400x400/?water,big',true,'Água',false,false,null),
('ag-015','continente-guarda','Caramulo 1.5L','Água mineral natural 1.5L',0.59,'https://source.unsplash.com/400x400/?water,fresh',true,'Água',false,false,null),
('ag-016','continente-guarda','Caramulo com Gás 75cl','Água com gás 75cl',0.89,'https://source.unsplash.com/400x400/?gas,water',true,'Água',false,false,null),
('ag-017','continente-guarda','Evian 1.5L','Água mineral francesa 1.5L',1.79,'https://source.unsplash.com/400x400/?evian,premium',true,'Água',false,false,null),
('ag-018','continente-guarda','Volvic 1.5L','Água mineral vulcânica 1.5L',1.49,'https://source.unsplash.com/400x400/?volvic,water',true,'Água',false,false,null),
('ag-019','continente-guarda','Perrier com Gás 33cl','Água mineral com gás 33cl',1.09,'https://source.unsplash.com/400x400/?perrier,sparkling',true,'Água',false,false,null),
('ag-020','continente-guarda','San Pellegrino 75cl','Água mineral italiana com gás 75cl',1.49,'https://source.unsplash.com/400x400/?san,pellegrino',true,'Água',false,false,null),
('ag-021','continente-guarda','Monchique Alcalina 1.5L','Água alcalina natural 1.5L',1.29,'https://source.unsplash.com/400x400/?alkaline,water',true,'Água',false,false,null),
('ag-022','continente-guarda','Continente Água 1.5L','Água mineral marca própria 1.5L',0.35,'https://source.unsplash.com/400x400/?water,simple',true,'Água',false,false,null),
('ag-023','continente-guarda','Continente Água 6x1.5L','Pack água marca própria 6 garrafas',1.89,'https://source.unsplash.com/400x400/?water,economy',true,'Água',true,false,null),
('ag-024','continente-guarda','Continente Água 5L','Água mineral 5L marca própria',0.99,'https://source.unsplash.com/400x400/?water,economy,big',true,'Água',false,false,null),
('ag-025','continente-guarda','Luso Aromas Limão 33cl','Água saborizada limão 33cl',0.55,'https://source.unsplash.com/400x400/?lemon,flavored,water',true,'Água',false,false,null),
('ag-026','continente-guarda','Luso Aromas Morango 33cl','Água saborizada morango 33cl',0.55,'https://source.unsplash.com/400x400/?strawberry,water',true,'Água',false,false,null),
('ag-027','continente-guarda','Luso Aromas Pêssego 33cl','Água saborizada pêssego 33cl',0.55,'https://source.unsplash.com/400x400/?peach,water',true,'Água',false,false,null),
('ag-028','continente-guarda','Luso Aromas Laranja 33cl','Água saborizada laranja 33cl',0.55,'https://source.unsplash.com/400x400/?orange,flavored,water',true,'Água',false,false,null),
('ag-029','continente-guarda','Fontes de Carvalho 1.5L','Água natural transmontana 1.5L',0.49,'https://source.unsplash.com/400x400/?natural,spring,water',true,'Água',false,false,null),
('ag-030','continente-guarda','Serra da Estrela 1.5L','Água mineral da Serra 1.5L',0.59,'https://source.unsplash.com/400x400/?mountain,water',true,'Água',false,false,null),
('ag-031','continente-guarda','Aquarel 6x1.5L','Pack água mineral económico',2.49,'https://source.unsplash.com/400x400/?water,value,pack',true,'Água',true,true,1.99),
('ag-032','continente-guarda','Smartwater 600ml','Água purificada premium 600ml',1.89,'https://source.unsplash.com/400x400/?smart,water',true,'Água',false,false,null),
('ag-033','continente-guarda','Frisada com Gás 1.5L','Água com gás garrafa grande',0.69,'https://source.unsplash.com/400x400/?fizzy,water',true,'Água',false,false,null),
('ag-034','continente-guarda','Luso 12x50cl','Pack água mineral 12 garrafinhas',4.49,'https://source.unsplash.com/400x400/?water,multipack,small',true,'Água',false,false,null),
('ag-035','continente-guarda','Água das Pedras Original 75cl','Água natural com gás original 75cl',1.09,'https://source.unsplash.com/400x400/?pedras,natural',true,'Água',false,false,null),

-- ── ICE TEA ──────────────────────────────────────────────────
('it-001','continente-guarda','Lipton Ice Tea Pêssego 33cl','Chá frio pêssego lata 33cl',0.79,'https://source.unsplash.com/400x400/?iced,tea,peach',true,'Ice Tea',true,false,null),
('it-002','continente-guarda','Lipton Ice Tea Pêssego 1.5L','Chá frio pêssego garrafa 1.5L',1.29,'https://source.unsplash.com/400x400/?ice,tea,bottle',true,'Ice Tea',true,false,null),
('it-003','continente-guarda','Lipton Ice Tea Limão 33cl','Chá frio limão lata 33cl',0.79,'https://source.unsplash.com/400x400/?ice,tea,lemon',true,'Ice Tea',true,false,null),
('it-004','continente-guarda','Lipton Ice Tea Limão 1.5L','Chá frio limão garrafa 1.5L',1.29,'https://source.unsplash.com/400x400/?lemon,tea,cold',true,'Ice Tea',false,false,null),
('it-005','continente-guarda','Lipton Ice Tea Manga 33cl','Chá frio manga lata 33cl',0.79,'https://source.unsplash.com/400x400/?mango,tea,cold',true,'Ice Tea',false,false,null),
('it-006','continente-guarda','Lipton Ice Tea Manga 1.5L','Chá frio manga garrafa 1.5L',1.29,'https://source.unsplash.com/400x400/?mango,iced,tea',true,'Ice Tea',false,false,null),
('it-007','continente-guarda','Lipton Ice Tea Zero Pêssego 33cl','Chá frio zero açúcar pêssego 33cl',0.79,'https://source.unsplash.com/400x400/?zero,tea,peach',true,'Ice Tea',false,false,null),
('it-008','continente-guarda','Lipton Ice Tea Zero Limão 33cl','Chá frio zero açúcar limão 33cl',0.79,'https://source.unsplash.com/400x400/?zero,iced,tea',true,'Ice Tea',false,false,null),
('it-009','continente-guarda','Lipton Ice Tea Verde Limão 33cl','Chá verde frio limão 33cl',0.79,'https://source.unsplash.com/400x400/?green,ice,tea',true,'Ice Tea',false,false,null),
('it-010','continente-guarda','Lipton Ice Tea Morango 33cl','Chá frio morango lata 33cl',0.79,'https://source.unsplash.com/400x400/?strawberry,iced,tea',true,'Ice Tea',false,false,null),
('it-011','continente-guarda','Nestea Pêssego 33cl','Chá frio pêssego Nestea 33cl',0.79,'https://source.unsplash.com/400x400/?nestea,peach',true,'Ice Tea',false,false,null),
('it-012','continente-guarda','Nestea Limão 33cl','Chá frio limão Nestea 33cl',0.79,'https://source.unsplash.com/400x400/?nestea,lemon',true,'Ice Tea',false,false,null),
('it-013','continente-guarda','Nestea Pêssego 1.5L','Chá frio pêssego Nestea garrafa',1.29,'https://source.unsplash.com/400x400/?nestea,bottle',true,'Ice Tea',false,false,null),
('it-014','continente-guarda','Fuze Tea Limão 400ml','Chá verde limão e menta 400ml',0.99,'https://source.unsplash.com/400x400/?fuze,tea,lemon',true,'Ice Tea',false,false,null),
('it-015','continente-guarda','Fuze Tea Pêssego 400ml','Chá preto pêssego 400ml',0.99,'https://source.unsplash.com/400x400/?fuze,peach,tea',true,'Ice Tea',false,false,null),
('it-016','continente-guarda','Fuze Tea Manga 400ml','Chá manga hibisco 400ml',0.99,'https://source.unsplash.com/400x400/?fuze,mango,hibiscus',true,'Ice Tea',false,false,null),
('it-017','continente-guarda','Arizona Pêssego 50cl','Chá frio pêssego americano 50cl',1.19,'https://source.unsplash.com/400x400/?arizona,tea',true,'Ice Tea',false,false,null),
('it-018','continente-guarda','Arizona Limão 50cl','Chá frio limão americano 50cl',1.19,'https://source.unsplash.com/400x400/?arizona,lemon,tea',true,'Ice Tea',false,false,null),
('it-019','continente-guarda','Lipton Pack 6x33cl Pêssego','Pack chá frio pêssego 6 latas',3.99,'https://source.unsplash.com/400x400/?iced,tea,pack',true,'Ice Tea',false,false,null),
('it-020','continente-guarda','Gold Ice Tea Pêssego 33cl','Chá frio pêssego marca própria 33cl',0.55,'https://source.unsplash.com/400x400/?iced,tea,economy',true,'Ice Tea',false,false,null),

-- ── CERVEJA ──────────────────────────────────────────────────
('cv-001','continente-guarda','Sagres 33cl','Cerveja nacional lata 33cl',0.79,'https://source.unsplash.com/400x400/?beer,can',true,'Cerveja',true,false,null),
('cv-002','continente-guarda','Sagres 50cl','Cerveja nacional lata 50cl',1.09,'https://source.unsplash.com/400x400/?beer,large,can',true,'Cerveja',true,false,null),
('cv-003','continente-guarda','Sagres 6x33cl','Pack cerveja nacional 6 latas',4.19,'https://source.unsplash.com/400x400/?beer,pack,6',true,'Cerveja',true,true,3.79),
('cv-004','continente-guarda','Sagres 24x33cl','Fardo cerveja nacional 24 latas',14.99,'https://source.unsplash.com/400x400/?beer,fardo',true,'Cerveja',true,false,null),
('cv-005','continente-guarda','Sagres Sem Álcool 33cl','Cerveja sem álcool lata 33cl',0.79,'https://source.unsplash.com/400x400/?non,alcoholic,beer',true,'Cerveja',false,false,null),
('cv-006','continente-guarda','Sagres Radler Limão 33cl','Cerveja com limão lata 33cl',0.89,'https://source.unsplash.com/400x400/?radler,lemon,beer',true,'Cerveja',false,false,null),
('cv-007','continente-guarda','Sagres Bohemia 33cl','Cerveja premium lata 33cl',0.99,'https://source.unsplash.com/400x400/?premium,beer',true,'Cerveja',false,false,null),
('cv-008','continente-guarda','Sagres Preta 33cl','Cerveja preta lata 33cl',0.89,'https://source.unsplash.com/400x400/?dark,beer,black',true,'Cerveja',false,false,null),
('cv-009','continente-guarda','Super Bock 33cl','Cerveja nacional lata 33cl',0.79,'https://source.unsplash.com/400x400/?super,bock,beer',true,'Cerveja',true,false,null),
('cv-010','continente-guarda','Super Bock 50cl','Cerveja nacional lata 50cl',1.09,'https://source.unsplash.com/400x400/?beer,tall,can',true,'Cerveja',true,false,null),
('cv-011','continente-guarda','Super Bock 6x33cl','Pack cerveja 6 latas',4.19,'https://source.unsplash.com/400x400/?beer,sixpack',true,'Cerveja',true,true,3.79),
('cv-012','continente-guarda','Super Bock 24x33cl','Fardo cerveja 24 latas',14.99,'https://source.unsplash.com/400x400/?beer,case',true,'Cerveja',true,false,null),
('cv-013','continente-guarda','Super Bock Stout 33cl','Cerveja stout preta lata 33cl',0.99,'https://source.unsplash.com/400x400/?stout,beer,dark',true,'Cerveja',false,false,null),
('cv-014','continente-guarda','Super Bock Green 33cl','Cerveja verde sem glúten lata 33cl',0.89,'https://source.unsplash.com/400x400/?green,beer',true,'Cerveja',false,false,null),
('cv-015','continente-guarda','Super Bock Sem Álcool 33cl','Cerveja sem álcool lata 33cl',0.79,'https://source.unsplash.com/400x400/?alcohol,free,beer',true,'Cerveja',false,false,null),
('cv-016','continente-guarda','Super Bock Triplo Lúpulo 33cl','Cerveja triplo lúpulo 33cl',1.29,'https://source.unsplash.com/400x400/?triple,hops,beer',true,'Cerveja',false,false,null),
('cv-017','continente-guarda','Heineken 33cl','Cerveja holandesa lata 33cl',0.99,'https://source.unsplash.com/400x400/?heineken,beer',true,'Cerveja',true,false,null),
('cv-018','continente-guarda','Heineken 50cl','Cerveja holandesa lata 50cl',1.29,'https://source.unsplash.com/400x400/?heineken,large',true,'Cerveja',false,false,null),
('cv-019','continente-guarda','Heineken 6x33cl','Pack cerveja holandesa 6 latas',5.49,'https://source.unsplash.com/400x400/?heineken,pack',true,'Cerveja',true,false,null),
('cv-020','continente-guarda','Heineken 0.0 33cl','Cerveja sem álcool holandesa 33cl',0.99,'https://source.unsplash.com/400x400/?heineken,zero',true,'Cerveja',false,false,null),
('cv-021','continente-guarda','Estrella Damm 33cl','Cerveja espanhola premium lata 33cl',0.99,'https://source.unsplash.com/400x400/?estrella,beer',true,'Cerveja',false,false,null),
('cv-022','continente-guarda','Estrella Damm 6x33cl','Pack cerveja espanhola 6 latas',5.29,'https://source.unsplash.com/400x400/?estrella,pack',true,'Cerveja',false,false,null),
('cv-023','continente-guarda','Corona 33cl','Cerveja mexicana garrafa 33cl',1.29,'https://source.unsplash.com/400x400/?corona,beer,bottle',true,'Cerveja',true,false,null),
('cv-024','continente-guarda','Corona 6x33cl','Pack cerveja mexicana 6 garrafas',6.99,'https://source.unsplash.com/400x400/?corona,sixpack',true,'Cerveja',false,false,null),
('cv-025','continente-guarda','Budweiser 33cl','Cerveja americana lata 33cl',0.99,'https://source.unsplash.com/400x400/?budweiser,beer',true,'Cerveja',false,false,null),
('cv-026','continente-guarda','Budweiser 6x33cl','Pack cerveja americana 6 latas',4.99,'https://source.unsplash.com/400x400/?budweiser,pack',true,'Cerveja',false,false,null),
('cv-027','continente-guarda','Sol 33cl','Cerveja mexicana clara garrafa 33cl',0.99,'https://source.unsplash.com/400x400/?sol,beer,lime',true,'Cerveja',false,false,null),
('cv-028','continente-guarda','Carlsberg 33cl','Cerveja dinamarquesa lata 33cl',0.89,'https://source.unsplash.com/400x400/?carlsberg,beer',true,'Cerveja',false,false,null),
('cv-029','continente-guarda','Carlsberg 6x33cl','Pack cerveja dinamarquesa 6 latas',4.49,'https://source.unsplash.com/400x400/?carlsberg,pack',true,'Cerveja',false,false,null),
('cv-030','continente-guarda','NOS Lager 33cl','Cerveja portuguesa NOS 33cl',0.79,'https://source.unsplash.com/400x400/?lager,beer,portuguese',true,'Cerveja',false,false,null),
('cv-031','continente-guarda','Bandida do Pomar 33cl','Cidra portuguesa 33cl',1.29,'https://source.unsplash.com/400x400/?cider,apple',true,'Cerveja',true,false,null),
('cv-032','continente-guarda','Bavaria 33cl','Cerveja holandesa económica 33cl',0.79,'https://source.unsplash.com/400x400/?bavaria,beer',true,'Cerveja',false,false,null),
('cv-033','continente-guarda','Leffe Blonde 33cl','Cerveja abadia belga 33cl',1.49,'https://source.unsplash.com/400x400/?leffe,abbey,beer',true,'Cerveja',false,false,null),
('cv-034','continente-guarda','Leffe Brune 33cl','Cerveja abadia escura belga 33cl',1.49,'https://source.unsplash.com/400x400/?leffe,brown,beer',true,'Cerveja',false,false,null),
('cv-035','continente-guarda','Guinness 44cl','Cerveja irlandesa stout 44cl',1.79,'https://source.unsplash.com/400x400/?guinness,stout',true,'Cerveja',true,false,null),
('cv-036','continente-guarda','Kilkenny 44cl','Cerveja irish red ale 44cl',1.79,'https://source.unsplash.com/400x400/?kilkenny,red,ale',true,'Cerveja',false,false,null),
('cv-037','continente-guarda','Hoegaarden 33cl','Cerveja belga de trigo 33cl',1.49,'https://source.unsplash.com/400x400/?hoegaarden,wheat,beer',true,'Cerveja',false,false,null),
('cv-038','continente-guarda','Amstel 33cl','Cerveja holandesa 33cl',0.89,'https://source.unsplash.com/400x400/?amstel,beer',true,'Cerveja',false,false,null),
('cv-039','continente-guarda','Birra Moretti 33cl','Cerveja italiana premium 33cl',0.99,'https://source.unsplash.com/400x400/?moretti,italian,beer',true,'Cerveja',false,false,null),
('cv-040','continente-guarda','Peroni 33cl','Cerveja italiana lager 33cl',1.09,'https://source.unsplash.com/400x400/?peroni,beer',true,'Cerveja',false,false,null),
('cv-041','continente-guarda','Paulaner 50cl','Cerveja alemã weiss 50cl',1.69,'https://source.unsplash.com/400x400/?paulaner,weiss',true,'Cerveja',false,false,null),
('cv-042','continente-guarda','Weihenstephaner 50cl','Cerveja alemã hefe 50cl',1.89,'https://source.unsplash.com/400x400/?weihenstephaner,german',true,'Cerveja',false,false,null),
('cv-043','continente-guarda','Kronenbourg 1664 33cl','Cerveja francesa premium 33cl',1.09,'https://source.unsplash.com/400x400/?kronenbourg,french,beer',true,'Cerveja',false,false,null),
('cv-044','continente-guarda','Modelo Especial 33cl','Cerveja mexicana 33cl',1.19,'https://source.unsplash.com/400x400/?modelo,mexican,beer',true,'Cerveja',false,false,null),
('cv-045','continente-guarda','Desperados 33cl','Cerveja tequila 33cl',1.49,'https://source.unsplash.com/400x400/?desperados,tequila,beer',true,'Cerveja',true,false,null),
('cv-046','continente-guarda','Coral 33cl','Cerveja dos Açores lata 33cl',0.79,'https://source.unsplash.com/400x400/?coral,azores,beer',true,'Cerveja',false,false,null),
('cv-047','continente-guarda','Brahma 33cl','Cerveja brasileira 33cl',0.79,'https://source.unsplash.com/400x400/?brahma,beer',true,'Cerveja',false,false,null),
('cv-048','continente-guarda','Sagres Radler Toranja 33cl','Cerveja com toranja 33cl',0.89,'https://source.unsplash.com/400x400/?radler,grapefruit',true,'Cerveja',false,false,null),
('cv-049','continente-guarda','Super Bock Abadia 33cl','Cerveja especial abadia 33cl',1.19,'https://source.unsplash.com/400x400/?abbey,special,beer',true,'Cerveja',false,false,null),
('cv-050','continente-guarda','Chouffe 33cl','Cerveja belga artesanal 33cl',1.99,'https://source.unsplash.com/400x400/?artisan,craft,beer',true,'Cerveja',false,false,null)

ON CONFLICT (id) DO NOTHING;
